//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace QiaoxingWebService
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "loginSoapBinding", Namespace = "http://172.16.71.28/portal5.0/services/login.jws")]
    public partial class loginService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getLoginInfoOperationCompleted;

        private System.Threading.SendOrPostCallback getCertKGOperationCompleted;

        private System.Threading.SendOrPostCallback getPINOperationCompleted;

        private System.Threading.SendOrPostCallback getUserInfoOperationCompleted;

        /// <remarks/>
        public loginService()
        {
            this.Url = "http://172.16.71.28/portal5.0/services/login.jws";
        }

        /// <remarks/>
        public event getLoginInfoCompletedEventHandler getLoginInfoCompleted;

        /// <remarks/>
        public event getCertKGCompletedEventHandler getCertKGCompleted;

        /// <remarks/>
        public event getPINCompletedEventHandler getPINCompleted;

        /// <remarks/>
        public event getUserInfoCompletedEventHandler getUserInfoCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://Portal5", ResponseNamespace = "http://172.16.71.28/portal5.0/services/login.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getLoginInfoReturn")]
        public string getLoginInfo(string cookies, string obj)
        {
            object[] results = this.Invoke("getLoginInfo", new object[] {
                        cookies,
                        obj});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetLoginInfo(string cookies, string obj, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getLoginInfo", new object[] {
                        cookies,
                        obj}, callback, asyncState);
        }

        /// <remarks/>
        public string EndgetLoginInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void getLoginInfoAsync(string cookies, string obj)
        {
            this.getLoginInfoAsync(cookies, obj, null);
        }

        /// <remarks/>
        public void getLoginInfoAsync(string cookies, string obj, object userState)
        {
            if ((this.getLoginInfoOperationCompleted == null))
            {
                this.getLoginInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLoginInfoOperationCompleted);
            }
            this.InvokeAsync("getLoginInfo", new object[] {
                        cookies,
                        obj}, this.getLoginInfoOperationCompleted, userState);
        }

        private void OngetLoginInfoOperationCompleted(object arg)
        {
            if ((this.getLoginInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLoginInfoCompleted(this, new getLoginInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://Portal5", ResponseNamespace = "http://172.16.71.28/portal5.0/services/login.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getCertKGReturn")]
        public bool getCertKG(string userID, string pw, string mode)
        {
            object[] results = this.Invoke("getCertKG", new object[] {
                        userID,
                        pw,
                        mode});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetCertKG(string userID, string pw, string mode, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getCertKG", new object[] {
                        userID,
                        pw,
                        mode}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndgetCertKG(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void getCertKGAsync(string userID, string pw, string mode)
        {
            this.getCertKGAsync(userID, pw, mode, null);
        }

        /// <remarks/>
        public void getCertKGAsync(string userID, string pw, string mode, object userState)
        {
            if ((this.getCertKGOperationCompleted == null))
            {
                this.getCertKGOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCertKGOperationCompleted);
            }
            this.InvokeAsync("getCertKG", new object[] {
                        userID,
                        pw,
                        mode}, this.getCertKGOperationCompleted, userState);
        }

        private void OngetCertKGOperationCompleted(object arg)
        {
            if ((this.getCertKGCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCertKGCompleted(this, new getCertKGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://Portal5", ResponseNamespace = "http://172.16.71.28/portal5.0/services/login.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPINReturn")]
        public string getPIN(string userID, string pw, string mode)
        {
            object[] results = this.Invoke("getPIN", new object[] {
                        userID,
                        pw,
                        mode});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetPIN(string userID, string pw, string mode, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getPIN", new object[] {
                        userID,
                        pw,
                        mode}, callback, asyncState);
        }

        /// <remarks/>
        public string EndgetPIN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void getPINAsync(string userID, string pw, string mode)
        {
            this.getPINAsync(userID, pw, mode, null);
        }

        /// <remarks/>
        public void getPINAsync(string userID, string pw, string mode, object userState)
        {
            if ((this.getPINOperationCompleted == null))
            {
                this.getPINOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPINOperationCompleted);
            }
            this.InvokeAsync("getPIN", new object[] {
                        userID,
                        pw,
                        mode}, this.getPINOperationCompleted, userState);
        }

        private void OngetPINOperationCompleted(object arg)
        {
            if ((this.getPINCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPINCompleted(this, new getPINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://Portal5", ResponseNamespace = "http://172.16.71.28/portal5.0/services/login.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUserInfoReturn")]
        public string getUserInfo(string userID, string obj)
        {
            object[] results = this.Invoke("getUserInfo", new object[] {
                        userID,
                        obj});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetUserInfo(string userID, string obj, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getUserInfo", new object[] {
                        userID,
                        obj}, callback, asyncState);
        }

        /// <remarks/>
        public string EndgetUserInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void getUserInfoAsync(string userID, string obj)
        {
            this.getUserInfoAsync(userID, obj, null);
        }

        /// <remarks/>
        public void getUserInfoAsync(string userID, string obj, object userState)
        {
            if ((this.getUserInfoOperationCompleted == null))
            {
                this.getUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserInfoOperationCompleted);
            }
            this.InvokeAsync("getUserInfo", new object[] {
                        userID,
                        obj}, this.getUserInfoOperationCompleted, userState);
        }

        private void OngetUserInfoOperationCompleted(object arg)
        {
            if ((this.getUserInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserInfoCompleted(this, new getUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getLoginInfoCompletedEventHandler(object sender, getLoginInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLoginInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getLoginInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getCertKGCompletedEventHandler(object sender, getCertKGCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCertKGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getCertKGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getPINCompletedEventHandler(object sender, getPINCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getPINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getUserInfoCompletedEventHandler(object sender, getUserInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
