//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace Yinhe.WebReference.Schdeuler {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JobRegisterSoap", Namespace="http://tempuri.org/")]
    public partial class JobRegister : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSysMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMobileSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTaskNoticeOnceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDesignSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendInstanceApproverNoticeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JobRegister() {
            this.Url = global::Yinhe.WebReference.Properties.Settings.Default.Yinhe_WebReference_Schdeuler_JobRegister;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWordCompletedEventHandler HelloWordCompleted;
        
        /// <remarks/>
        public event SendSysMessageCompletedEventHandler SendSysMessageCompleted;
        
        /// <remarks/>
        public event SendMobileSMSCompletedEventHandler SendMobileSMSCompleted;
        
        /// <remarks/>
        public event RemoveJobCompletedEventHandler RemoveJobCompleted;
        
        /// <remarks/>
        public event SendTaskNoticeOnceCompletedEventHandler SendTaskNoticeOnceCompleted;
        
        /// <remarks/>
        public event DeleteDesignSupplierCompletedEventHandler DeleteDesignSupplierCompleted;
        
        /// <remarks/>
        public event SendInstanceApproverNoticeCompletedEventHandler SendInstanceApproverNoticeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWord(string html) {
            object[] results = this.Invoke("HelloWord", new object[] {
                        html});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWordAsync(string html) {
            this.HelloWordAsync(html, null);
        }
        
        /// <remarks/>
        public void HelloWordAsync(string html, object userState) {
            if ((this.HelloWordOperationCompleted == null)) {
                this.HelloWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWordOperationCompleted);
            }
            this.InvokeAsync("HelloWord", new object[] {
                        html}, this.HelloWordOperationCompleted, userState);
        }
        
        private void OnHelloWordOperationCompleted(object arg) {
            if ((this.HelloWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWordCompleted(this, new HelloWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSysMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendSysMessage(Group group, string jobName, System.DateTime sendTime, SystemMsg msg) {
            this.Invoke("SendSysMessage", new object[] {
                        group,
                        jobName,
                        sendTime,
                        msg});
        }
        
        /// <remarks/>
        public void SendSysMessageAsync(Group group, string jobName, System.DateTime sendTime, SystemMsg msg) {
            this.SendSysMessageAsync(group, jobName, sendTime, msg, null);
        }
        
        /// <remarks/>
        public void SendSysMessageAsync(Group group, string jobName, System.DateTime sendTime, SystemMsg msg, object userState) {
            if ((this.SendSysMessageOperationCompleted == null)) {
                this.SendSysMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSysMessageOperationCompleted);
            }
            this.InvokeAsync("SendSysMessage", new object[] {
                        group,
                        jobName,
                        sendTime,
                        msg}, this.SendSysMessageOperationCompleted, userState);
        }
        
        private void OnSendSysMessageOperationCompleted(object arg) {
            if ((this.SendSysMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSysMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMobileSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMobileSMS(Group group, System.DateTime sendTime, MobileSMS sms) {
            this.Invoke("SendMobileSMS", new object[] {
                        group,
                        sendTime,
                        sms});
        }
        
        /// <remarks/>
        public void SendMobileSMSAsync(Group group, System.DateTime sendTime, MobileSMS sms) {
            this.SendMobileSMSAsync(group, sendTime, sms, null);
        }
        
        /// <remarks/>
        public void SendMobileSMSAsync(Group group, System.DateTime sendTime, MobileSMS sms, object userState) {
            if ((this.SendMobileSMSOperationCompleted == null)) {
                this.SendMobileSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMobileSMSOperationCompleted);
            }
            this.InvokeAsync("SendMobileSMS", new object[] {
                        group,
                        sendTime,
                        sms}, this.SendMobileSMSOperationCompleted, userState);
        }
        
        private void OnSendMobileSMSOperationCompleted(object arg) {
            if ((this.SendMobileSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMobileSMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveJob(Group group, string jobName) {
            object[] results = this.Invoke("RemoveJob", new object[] {
                        group,
                        jobName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveJobAsync(Group group, string jobName) {
            this.RemoveJobAsync(group, jobName, null);
        }
        
        /// <remarks/>
        public void RemoveJobAsync(Group group, string jobName, object userState) {
            if ((this.RemoveJobOperationCompleted == null)) {
                this.RemoveJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveJobOperationCompleted);
            }
            this.InvokeAsync("RemoveJob", new object[] {
                        group,
                        jobName}, this.RemoveJobOperationCompleted, userState);
        }
        
        private void OnRemoveJobOperationCompleted(object arg) {
            if ((this.RemoveJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveJobCompleted(this, new RemoveJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTaskNoticeOnce", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendTaskNoticeOnce(Group group, string jobName, string cronEx) {
            this.Invoke("SendTaskNoticeOnce", new object[] {
                        group,
                        jobName,
                        cronEx});
        }
        
        /// <remarks/>
        public void SendTaskNoticeOnceAsync(Group group, string jobName, string cronEx) {
            this.SendTaskNoticeOnceAsync(group, jobName, cronEx, null);
        }
        
        /// <remarks/>
        public void SendTaskNoticeOnceAsync(Group group, string jobName, string cronEx, object userState) {
            if ((this.SendTaskNoticeOnceOperationCompleted == null)) {
                this.SendTaskNoticeOnceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTaskNoticeOnceOperationCompleted);
            }
            this.InvokeAsync("SendTaskNoticeOnce", new object[] {
                        group,
                        jobName,
                        cronEx}, this.SendTaskNoticeOnceOperationCompleted, userState);
        }
        
        private void OnSendTaskNoticeOnceOperationCompleted(object arg) {
            if ((this.SendTaskNoticeOnceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTaskNoticeOnceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteDesignSupplier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteDesignSupplier(Group group, string jobName, string cronEx) {
            this.Invoke("DeleteDesignSupplier", new object[] {
                        group,
                        jobName,
                        cronEx});
        }
        
        /// <remarks/>
        public void DeleteDesignSupplierAsync(Group group, string jobName, string cronEx) {
            this.DeleteDesignSupplierAsync(group, jobName, cronEx, null);
        }
        
        /// <remarks/>
        public void DeleteDesignSupplierAsync(Group group, string jobName, string cronEx, object userState) {
            if ((this.DeleteDesignSupplierOperationCompleted == null)) {
                this.DeleteDesignSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDesignSupplierOperationCompleted);
            }
            this.InvokeAsync("DeleteDesignSupplier", new object[] {
                        group,
                        jobName,
                        cronEx}, this.DeleteDesignSupplierOperationCompleted, userState);
        }
        
        private void OnDeleteDesignSupplierOperationCompleted(object arg) {
            if ((this.DeleteDesignSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDesignSupplierCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendInstanceApproverNotice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendInstanceApproverNotice(Group group, string jobName, string cronEx) {
            this.Invoke("SendInstanceApproverNotice", new object[] {
                        group,
                        jobName,
                        cronEx});
        }
        
        /// <remarks/>
        public void SendInstanceApproverNoticeAsync(Group group, string jobName, string cronEx) {
            this.SendInstanceApproverNoticeAsync(group, jobName, cronEx, null);
        }
        
        /// <remarks/>
        public void SendInstanceApproverNoticeAsync(Group group, string jobName, string cronEx, object userState) {
            if ((this.SendInstanceApproverNoticeOperationCompleted == null)) {
                this.SendInstanceApproverNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendInstanceApproverNoticeOperationCompleted);
            }
            this.InvokeAsync("SendInstanceApproverNotice", new object[] {
                        group,
                        jobName,
                        cronEx}, this.SendInstanceApproverNoticeOperationCompleted, userState);
        }
        
        private void OnSendInstanceApproverNoticeOperationCompleted(object arg) {
            if ((this.SendInstanceApproverNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendInstanceApproverNoticeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Group {
        
        /// <remarks/>
        Msg_Persistent,
        
        /// <remarks/>
        Msg_CRM_Customer_UpdateStage,
        
        /// <remarks/>
        Msg_CRM_Customer_LeaveMsg,
        
        /// <remarks/>
        Msg_CRM_Customer_PopActivity,
        
        /// <remarks/>
        Msg_Contract_Mgr_ReceiptMileStone,
        
        /// <remarks/>
        Msg_Engineer_ProjectMgr_StartPlan,
        
        /// <remarks/>
        Msg_WF_Action_Normal,
        
        /// <remarks/>
        Msg_Result_ResultJudge,
        
        /// <remarks/>
        Msg_PlaningWorkTask,
        
        /// <remarks/>
        Msg_SubmitDocumentBill,
        
        /// <remarks/>
        Msg_ReplyPostil,
        
        /// <remarks/>
        Msg_ProjectResultComment,
        
        /// <remarks/>
        Msg_MobileSMS,
        
        /// <remarks/>
        Msg_StandardResult,
        
        /// <remarks/>
        Msg_DepartmentBudget,
        
        /// <remarks/>
        Msg_ZHTZ_DeleteDesignSupplier,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemMsg {
        
        private int senderIdField;
        
        private System.DateTime createDateField;
        
        private int typeIdField;
        
        private string titleField;
        
        private string contentField;
        
        private string contentHeadField;
        
        private string verificationCodeField;
        
        private string sMSContentField;
        
        private int[] toUserIdsField;
        
        private int[] cCUserIdsField;
        
        private bool sendEmailField;
        
        private bool sendMobileSMSField;
        
        private string hostField;
        
        private System.Nullable<int> srcTypeIdField;
        
        private System.Nullable<int> isImportantField;
        
        /// <remarks/>
        public int SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string ContentHead {
            get {
                return this.contentHeadField;
            }
            set {
                this.contentHeadField = value;
            }
        }
        
        /// <remarks/>
        public string VerificationCode {
            get {
                return this.verificationCodeField;
            }
            set {
                this.verificationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SMSContent {
            get {
                return this.sMSContentField;
            }
            set {
                this.sMSContentField = value;
            }
        }
        
        /// <remarks/>
        public int[] ToUserIds {
            get {
                return this.toUserIdsField;
            }
            set {
                this.toUserIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] CCUserIds {
            get {
                return this.cCUserIdsField;
            }
            set {
                this.cCUserIdsField = value;
            }
        }
        
        /// <remarks/>
        public bool SendEmail {
            get {
                return this.sendEmailField;
            }
            set {
                this.sendEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendMobileSMS {
            get {
                return this.sendMobileSMSField;
            }
            set {
                this.sendMobileSMSField = value;
            }
        }
        
        /// <remarks/>
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> srcTypeId {
            get {
                return this.srcTypeIdField;
            }
            set {
                this.srcTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> isImportant {
            get {
                return this.isImportantField;
            }
            set {
                this.isImportantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MobileSMS {
        
        private string contentField;
        
        private string verificationCodeField;
        
        private string[] phoneNumbersField;
        
        private int[] userIdsField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string verificationCode {
            get {
                return this.verificationCodeField;
            }
            set {
                this.verificationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string[] PhoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        public int[] UserIds {
            get {
                return this.userIdsField;
            }
            set {
                this.userIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWordCompletedEventHandler(object sender, HelloWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendSysMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendMobileSMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveJobCompletedEventHandler(object sender, RemoveJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendTaskNoticeOnceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteDesignSupplierCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendInstanceApproverNoticeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591