/*
Copyright 2013, MT, v1.0.0, build time: Jan 30 01:27
*/
MT.add("util-date",function(f){f.date={YEAR:"y",MONTH:"m",DAY:"d",HOUR:"h",MINUTE:"mi",SECOND:"s",MILLI:"ms",dayNames:{SUN:0,MON:1,TUE:2,WED:3,THU:4,FRI:5,SAT:6},monthNames:{JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11},isLeapYear:function(a){a=MT.isDate(a)?a.getFullYear():a;return!!(0===(a&3)&&(a%100||0===a%400&&a))},getGMTOffset:function(a,b){var c=a.getTimezoneOffset();return(0<c?"-":"+")+MT.string.leftPad(Math.floor(Math.abs(c)/60),2,"0")+(b?":":"")+MT.string.leftPad(Math.abs(c%
60),2,"0")},getDaysOfMonth:function(a,b){var c=[31,28,31,30,31,30,31,31,30,31,30,31],d,f;d=MT.isDate(a)?a.getMonth():a;f=b||(MT.isDate(a)?a:new Date);return 1==d&&e.isLeapYear(f)?29:c[d]},getDayOfYear:function(a){var b=a.getDate()-1,c=a.clone(a);a=a.getMonth();var d;c.setDate(1);c.setMonth(0);for(d=0;d<a;c.setMonth(++d))b+=e.getDaysOfMonth(c);return b},getWeekOfYear:function(a){a=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()+3)/864E5;a=Math.floor(a/7);var b=(new Date(6048E5*a)).getUTCFullYear();
return a-Math.floor(Date.UTC(b,0,7)/6048E5)+1},getFirstDateOfMonth:function(a){return new Date(a.getFullYear(),a.getMonth(),1)},getLastDateOfMonth:function(a){return new Date(a.getFullYear(),a.getMonth(),e.getDaysOfMonth(a))},getFirstDayOfMonth:function(a){return e.getFirstDateOfMonth(a).getDay()},getLastDayOfMonth:function(a){return e.getLastDateOfMonth(a).getDay()},format:function(a,b){var c={"M+":a.getMonth()+1,"d+":a.getDate(),"h+":a.getHours(),"m+":a.getMinutes(),"s+":a.getSeconds(),"q+":Math.floor((a.getMonth()+
3)/3),S:a.getMilliseconds()};/(y+)/.test(b)&&(b=b.replace(RegExp.$1,(a.getFullYear()+"").substr(4-RegExp.$1.length)));for(var d in c)RegExp("("+d+")").test(b)&&(b=b.replace(RegExp.$1,1==RegExp.$1.length?c[d]:("00"+c[d]).substr((""+c[d]).length)));return b},parse:function(a){a=Date.parse(a);return isNaN(a)?!1:!0}};var e=f.date;f.mixin(Date.prototype,{clone:function(){return new Date(this.getTime())},add:function(a,b){var c=this.clone();if(!a||0===b)return c;switch(a.toLowerCase()){case e.MILLI:c.setMilliseconds(this.getMilliseconds()+
b);break;case e.SECOND:c.setSeconds(this.getSeconds()+b);break;case e.MINUTE:c.setMinutes(this.getMinutes()+b);break;case e.HOUR:c.setHours(this.getHours()+b);break;case e.DAY:c.setDate(this.getDate()+b);break;case e.MONTH:var d=this.getDate();28<d&&(d=Math.min(d,e.getFirstDateOfMonth(this).add("mo",b).getLastDateOfMonth().getDate()));c.setDate(d);c.setMonth(this.getMonth()+b);break;case e.YEAR:c.setFullYear(this.getFullYear()+b)}return c},isBetween:function(a,b){var c=this.getTime();return a.getTime()<=
c&&c<=b.getTime()},getElapsed:function(a){return(a||new Date).getTime()-this.getTime()},format:Date.prototype.format?Date.prototype.format:function(a){return MT.date.format(this,a)}})});
