/*
Copyright 2011, A+ v1.0.0
build time: Oct 28 18:57
*/
var ppHelper={uniquekey:function(){return(new Date).getTime().toString(36)},getSecureUrl:function(){return YH.isIE6?"javascript:''":"javascript:void(0);"},cacheData:{},getBoxid:function(b){var j="";if(typeof b=="string")j=b+"__";else{b=$(b).parentsUntil(".ppbox").parent();if(b.length>0)j=b.attr("id")}return j}};
(function(b){function j(){p||(p=999);return++p}function k(){b(s).css({width:YH.dom.getDocumentWidth(h)+"px",height:YH.dom.getDocumentHeight(h)+"px"})}for(var e=window,h,n,p,s;e.parent!=e;)e=e.parent;h=e.document;var o=[];ppHelper.cacheData.arrPPBoxs=o;var w=function(a,c){this._content=a||"";this._options=c||{};this.btns=this.options=this.loadurl=this.selector=this.mh=this.db=this.dt=this.dd=this.fbox=null;this.defaults={boxid:null,title:null,width:"auto",height:"auto",ipos:null,cls:null,bodyCls:null,
cache:false,fixable:true,closable:true,draggable:true,IsLocked:false,range:true,modal:false,maskbgc:"#ccc",timeout:0,contentType:"html",loadingMessage:"Loading...",onLoad:b.noop,onOpen:b.noop,onClose:b.noop,onDestroy:b.noop,link:false,ajaxOptions:{},submit_BtnName:"\u786e \u5b9a",cancel_BtnName:"\u53d6 \u6d88",no_submit:false,no_titlebar:false,no_cancel:false,submit_cb:b.noop,cancel_cb:b.noop,regDragWindow:[],pos:"c-c",offset:null,setZIndex:true,prt:null};this.init()};w.prototype={parseOptions:function(){this._options.cls=
this._options.cls||"shadow-container";if(this._options.contentType=="")this._options.contentType=this._content.substr(0,1)=="#"?"selector":"html";this.options=b.extend({},this.defaults,this._options);this._defaults=this._options=null;if(this.options.SetTopWin){e=this.options.SetTopWin;h=e.document}ppHelper.cacheData.topWin=e},createFrame:function(){var a=this.options,c='<div class="ppbox">\t<div class="title" style="position:relative;'+(a.no_titlebar?"display:none;":"")+'">\t\t<div class="name" style="margin-right:40px;height:40px;overflow:hidden"></div>'+
(a.closable?'\t\t<div class="oper" style="position:absolute;right:4px;top:1px"><a href="javascript:void(0)" cl="close" title="\u5173\u95ed"></a></div>':"")+(a.fixable?'\t\t<div class="Expand" style="position:absolute;right:22px;top:1px"><a href="javascript:void(0)" cl="fix" status="move" title="\u53ef\u79fb\u52a8"></a></div>':"")+'\t</div>\t<table border="0" cellspacing="0" cellpadding="0" width="100%"><tr><td class="df_content" style="vertical-align:top;margin:0;padding:0"><div style="width:100%;height:100px;"></div></td></tr><tr><td><div class="myloading" style="position:absolute;top:45%;left:0%;height:25%;width:100%;text-align:center;"><img src="/Content/Images/zh-cn/Persons/loading19.gif"></div></td></tr></table></div>';
try{p||(p=j());this.fbox=b(c,h).appendTo(h.body).hide().css({position:"absolute",zIndex:a.zIndex||p});a.boxid=(!a.boxid?"bid__":a.boxid+"__")+ppHelper.uniquekey();this.dd=this.fbox.find(".title");this.dt=this.fbox.find(".name");this.dd.css("cursor","move");this.db=this.fbox.find(".df_content");this.dt.html(a.title||"");this.loading=this.fbox.find(".myloading");var d=a.no_submit?"":'<input type="button" id="submit_'+a.boxid+'" value="'+a.submit_BtnName+'" />',g=a.no_cancel?"":'\u3000<input type="button" id="cancel_'+
a.boxid+'" value="'+a.cancel_BtnName+'" />';this.btns=d!=""||g!=""?'<div class="bottom"><div class="btn">'+d+g+"</div></div>":"";this.fbox.attr("id",a.boxid);this.dd.attr("id","handler_"+a.boxid);a.cls&&this.fbox.addClass(a.cls);a.bodyCls&&this.db.addClass(a.bodyCls);a.height>0&&this.fbox.css("height",a.height);a.width>0&&this.fbox.css("width",a.width);a.IsLocked&&this.setFix("fixed");this.fbox.bgiframe();n||(n=b('<div id="proxy_div" style="position:absolute;top:0px;left:0px;border:1px solid #000;background-color:#999;display:none;"></div>',
h).css("opacity",0.3).appendTo(h.body).bind("contextmenu",function(q){q.preventDefault()})[0]);if(a.prt&&this.findObj(a.prt)){var f=this.findObj(a.prt);this.fbox.data("pbox",{p:f});var l=f.fbox.data("sbox")||[];l.push(this);f.fbox.data("sbox",l);l=f=null}}catch(r){return false}},initContent:function(){var a=this.options;if(a.contentType=="selector"){this.selector=this._content;a=b(this.selector);a.attr("class")&&this.fbox.removeClass("shadow-container").addClass(a.attr("class"));if(!a.data("htm")){a.data("htm",
a.wrapInner('<div assign="wrapin"></div>').html());a.empty()}this._content=a.data("htm")||""}else if(a.contentType=="ajax"){this.loadurl=this._content;if(a.cache==false)this.loadurl+=(/\?/.test(this.loadurl)?"&":"?")+"_t="+Math.random()}else if(a.contentType=="iframe"){this.loadurl=this._content;this._content='<iframe frameborder="0" scrolling="auto" class="dlgIframe" src="'+this.loadurl+'" style="display:none;width:100%;height:100%;"></iframe>'}this.LoadData()},__setPosition:function(){var a=this.fbox.getAlignToXY(h,
this.options.pos,this.options.offset,h);this.fbox.css({left:a.x,top:a.y});return a},LoadData:function(){var a=this,c=this.options;if(this.loadurl){c.onOpen(this);this.show();if(c.contentType=="iframe"){this.setContent(this._content);this.infrm=b(".dlgIframe",a.fbox)[0];if(!c.link){this.inwin=this.infrm.contentWindow;this.infrm.dg=this}b(this.infrm).bind("load",function(){if(!c.link){var f=b.browser.msie?this.contentWindow.document:this.contentWindow;c.setZIndex&&b(f).mousedown(function(){a.setIndex()});
a.regWindow.push(this.contentWindow)}a.loading.hide();this.style.display="block";c.onLoad(a)})}else{var d={type:"get",url:this.loadurl,success:function(f){a.db.hide();f=f.replace(/class=\"title\"/,'class="org_title_9527"');a.setContent(f);if(a.db.find(".org_title_9527")[0]){f=a.db.find(".org_title_9527");b(".name",f)[0]&&a.dt.html(b(".name",f).html());a.setFix(f.find("a[status]").attr("status"));f.empty().hide()}if(a.db.find("div[assign='box']")[0]){f=a.db.find("div[assign='box']");var l=f.attr("class")||
"";l&&a.fbox.removeClass("shadow-container").addClass(l);f.removeAttr("id").removeAttr("class").removeAttr("assign").removeAttr("style")}a.db.find(".bottom .btn").length==0&&a.db.append(a.btns);a.loading.hide();a.db.show();c.onLoad(a);a.show()},complete:function(){}};b.isEmptyObject(c.ajaxOptions)||(d=b.extend(d,c.ajaxOptions));b.ajax(d)}}else{a.db.hide();this.setContent(this._content);if(a.db.find("div[assign='wrapin']")[0]){d=a.db.find("div[assign='wrapin']");var g=false;b(".name",d)[0]&&a.dt.html(b(".name",
d).html());if(b(".title",d)[0]){g=true;a.setFix(b(".title",d).find("a[status]").attr("status"))}d=g?b(".title",d).nextAll():d.html();a.db.html(d);d=null}a.db.find(".bottom .btn").length==0&&a.db.append(a.btns);a.loading.hide();a.db.show();c.onOpen(this);this.show()}},initEvent:function(){var a=this,c=a.options;this.win=window;this.top=e;c.setZIndex&&this.fbox.mousedown(function(){a.setIndex()});c.modal&&this.showMask();c.closable&&this.fbox.find("div.oper>a").click(function(){a.destroy()});c.timeout>
0&&window.setTimeout(function(){a.destroy()},c.timeout*1E3);this.regWindow=[window];c.regDragWindow.length>0&&this.regWindow.push(c.regDragWindow);e!=window&&this.regWindow.push(e);this.initDrag(this.dd[0]);c.fixable&&this.fbox.find(".title div:last-child>a").click(function(){a.setFix("fixed",true)});c.no_submit||b("#submit_"+c.boxid,h).live("click",function(){c.submit_cb(a)!=false&&a.destroy()});c.no_cancel||b("#cancel_"+c.boxid,h).live("click",function(){c.cancel_cb(a)!=false&&a.destroy()})},setFix:function(a,
c){if(a){var d=this.dd.find("a[status]");if(a=="fixed"){d.parent().removeClass("Expand").addClass("Nails");d.attr({status:"fixed",title:"\u5df2\u56fa\u5b9a"});this.dd.css("cursor","default");if(c){this.__setPosition();this.fbox.center({left:this.fbox.css("left")})}this.options.draggable=false}else{d.parent().removeClass("Nails").addClass("Expand");d.attr({status:"move",title:"\u53ef\u79fb\u52a8"});this.dd.css("cursor","move");this.options.draggable=true}}},initDrag:function(a){function c(m){m={x:m.screenX,y:m.screenY};l={x:l.x+
(m.x-f.x),y:l.y+(m.y-f.y)};f=m;q[0]=l.x;q[1]=l.y;if(g.options.range)q=YH.dom.Bound(b(n),h,l.x,l.y);b(n).css({left:q[0]+"px",top:q[1]+"px"})}function d(){for(var m=0,u=r.length;m<u;m++){b(r[m].document).unbind("mousemove",c);b(r[m].document).unbind("mouseup",d)}b.browser.msie&&n.releaseCapture();b(n).hide();a=f=null;g.fbox.css({marginTop:0,marginLeft:0,left:q[0]+"px",top:q[1]+"px"})}var g=this,f,l,r=g.regWindow,q=[];b(a).bind("mousedown",function(m){g.dd.css("cursor","move");b(this).find("a[status]").attr({status:"move",
title:"\u53ef\u79fb\u52a8"}).parent().removeClass("Nails").addClass("Expand");if(!(m.target.getAttribute("cl")==="close"||m.target.getAttribute("cl")==="fix")){var u=g.fbox.offset().left,x=g.fbox.offset().top,t=g.fbox.outerWidth(),v=g.fbox.outerHeight();l={x:u,y:x};f={x:m.screenX,y:m.screenY};u=g.options.setZIndex?parseInt(p,10):parseInt(g.fbox.css("zIndex"),10);b(n).css({width:t-2+"px",height:v-2+"px",left:l.x+"px",top:l.y+"px",zIndex:u+2,display:""});t=0;for(v=r.length;t<v;t++){b(r[t].document).bind("mousemove",
c);b(r[t].document).bind("mouseup",d)}m.preventDefault();b.browser.msie&&n.setCapture()}})},setIndex:function(){this.fbox.css("zIndex",parseInt(p,10)+1);p=parseInt(this.fbox.css("zIndex"),10);if(b(this.fbox).data("sbox")){var a=this.fbox.data("sbox")||[];if(a.length>0)for(var c=0;c<a.length;c++){a[c].fbox.css("zIndex",parseInt(p,10)+1);p=parseInt(a[c].fbox.css("zIndex"),10)}}},getID:function(){return this.options.boxid},show:function(){this.__setPosition();this.fbox.show()},setCaption:function(a){this.dt.html(a)},
setContent:function(a){this.db.html(a)},hide:function(){this.fbox.hide();this.options.prt||this.hideMask()},destroy:function(){if(this.options.contentType=="iframe"){var a=this.fbox.find(".dlgIframe")[0];this.options.link||b(a.contentWindow).unbind("load");a.src=ppHelper.getSecureUrl();a=null}this.regWindow=[];if(this.fbox.data("sbox")){a=this.fbox.data("sbox")||[];if(a.length>0)for(var c=0;c<a.length;c++)a[c].destroy()}if(this.fbox.data("pbox")){c=this.fbox.data("pbox").p;var d=this;if(c){a=c.fbox.data("sbox")||
[];if(a.length>0){a=b.grep(a,function(g){return g!==d},false);c.fbox.data("sbox",a)}}}for(i=0;i<o.length;i++)if(o[i].fbox.get(0)==this.fbox.get(0)){o.splice(i,1);break}this.fbox.each(function(){b(this).remove();if(b.browser.msie)this.outerHTML=""});this.options.prt||this.hideMask();this.options.onClose(this);this.options.onDestroy(this)},find:function(a){return this.fbox.find(a)},showMask:function(){if(!s){var a=['<div style="position:absolute;top:0px;left:0px;',"background-color:"+this.options.maskbgc+
';">',YH.isIE6?'<iframe hideFocus="true" frameborder="0" src="'+ppHelper.getSecureUrl()+'" style="position:absolute;z-index:-1;width:100%;height:100%;top:0px;left:0px;filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0)"></iframe>':"","</div>"].join("");s=b(a,h).css("opacity",0.5).appendTo(h.body)[0]}b(e).bind("resize",k);k();b(s).css({display:"",zIndex:j()-2})},hideMask:function(){if(s)s.style.display="none"},findObj:function(a){if(a){for(var c=false,d=0;d<o.length;d++){var g=o[d].fbox.attr("id");
if(g==a||g.indexOf(a+"__")!=-1){c=o[d];break}}return c}},addBtn:function(a,c,d,g){var f=this;c='<input type="button" id="'+a+'" value="'+d+'"'+(c!=""?' class="'+c+'"':"")+" />";if(this.options.no_submit&&this.options.no_cancel&&!this.fbox.find(".bottom").get(0)){this.fbox.append('<div class="bottom"><div class="btn">'+c+"</div></div>");b("#"+a,f.fbox).click(function(){g.call(f)})}else{this.dbot=this.fbox.find(".bottom");if(b("#"+a,f.fbox)[0])b("#"+a,f.fbox).val(d).click(function(){g.call(f)});else{this.dbot.find(".btn").prepend("\u3000"+
c);b("#"+a,f.fbox).click(function(){g.call(f)})}}},removeBtn:function(a){if(b(a,this.fbox)[0]){b(a).remove();b.trim(this.fbox.find(".bottom>.btn").html()).length<3&&this.fbox.find(".bottom").remove()}},init:function(){this.parseOptions();this.createFrame();o.push(this);this.initContent();this.initEvent();return this}};b.extend({box:new function(){this.length=function(){return o.length};this.showbox=function(a,c){c=c||{};if(c.boxid&&c.one)for(var d=0;d<o.length;d++)if(o[d].fbox.attr("id").indexOf(c.boxid+
"__")!=-1){o[d].destroy();break}return new w(a,c)};this.close=function(){}}});b.fn.center=function(a){var c=b.extend({position:"absolute",top:"50%",left:"50%",relative:false},a||{}),d=ppHelper.cacheData.topWin;return this.each(function(){var g=b(this);if(c.top=="50%")c.marginTop=-g.outerHeight()/2;if(c.left=="50%")c.marginLeft=-g.outerWidth()/2;c.marginTop+=b(d.document).scrollTop();if(g.outerHeight()>=b(d).height())c.marginTop=-140;b(d).scroll(function(){if(g.find("a[status]").attr("status")=="fixed"){var f=
0;f=g.outerHeight()>=b(d).height()?-140:b(d.document).scrollTop()-g.outerHeight()/2;g.stop().animate({marginTop:f})}});g.css(c)})}})(jQuery);function box(b,j){return $.box.showbox(b,$.extend({},{one:true},j))}function findObjByBoxid(b){if(b){var j=false,k=ppHelper.cacheData.arrPPBoxs;b=ppHelper.getBoxid(b);for(var e=0;e<k.length;e++)if(k[e].fbox.attr("id").indexOf(b)!=-1){j=k[e];break}return j}}
function closeById(b){if(b){var j=ppHelper.cacheData.arrPPBoxs,k;if(k=ppHelper.getBoxid(b))for(b=0;b<j.length;b++){if(j[b].fbox.attr("id").indexOf(k)!=-1){j[b].destroy();break}}else HideBox(b)}}function setCenterAfterLoad(b){(b=findObjByBoxid(b))&&b.fbox.center()}
function JSONToString(b){function j(e){switch(typeof e){case "undefined":return k(e);case "boolean":return k(e);case "number":return k(e);case "string":return'"'+e+'"';case "function":e=e.toString();if(e.search(/\[native\s+code\]/i)==-1)return e;else return(e=e.match(/function\s+(.+)\(/i))?e[1]:k(undefined);case "object":if(e===null)return k(e);switch(e.constructor){case Object:var h,n="";for(h in e)if(e.hasOwnProperty(h))n+='"'+h+'":'+j(e[h])+",";return"{"+n.replace(/,$/i,"")+"}";case Array:n="";
for(h in e)if(e.hasOwnProperty(h))n+=j(e[h])+",";return"["+n.replace(/,$/i,"")+"]";case RegExp:return k(e);case Function:return e.toString();case String:return'"'+e.valueOf()+'"';case Number:return k(e.valueOf());case Boolean:return k(e.valueOf())}}}if(b.constructor===Object){var k=String;return j(b)}else return b}function stringToJSON(b){return eval("("+b+")")};
