/*
Copyright 2012, A+ v1.0.0
build time: Jul 31 16:18
*/
var YH={furl:"/Content/Images/zh-cn/"};
(function(a){var b=0,d=!window.XMLHttpRequest&&window.ActiveXObject,e=document.compatMode=="CSS1Compat";YH.userAgent={isIE:a.browser.msie,isGecko:a.browser.mozilla,isWebkit:a.browser.webkit,isOpera:a.browser.opera,isVersion:function(c){return String.compareVersions(a.browser.version,c)>=0}};a.extend(YH,{isStrict:e,isIE6:d,applyIf:function(c,h){if(c)for(var f in h)if(a.isEmptyObject(c[f]))c[f]=h[f];return c},genId:function(c){return(c||"auto-gen")+ ++b},isdefined:function(c){return typeof c!=="undefined"},
$id:function(c){if(c instanceof jQuery)return c.get(0);return typeof c=="string"?document.getElementById(c):c},isEmpty:function(c,h){return c===null||c===undefined||a.isArray(c)&&!c.length||(!h?c==="":false)},loadCSS:function(c,h){if(!this.$id(h))if(/\w+\.\w+(\?|$)/.test(c)){var f=document.getElementsByTagName("head")[0];a(document.createElement("link")).attr({type:"text/css",href:c,id:h,rel:"stylesheet",media:"screen"}).appendTo(f)}},loadJS:function(c,h,f){c={type:"GET",url:c,success:h,dataType:"script",
cache:false};a.extend(c,f);a.ajax(c)},loadXML:function(c,h){var f,i=h||0;if(window.ActiveXObject){for(var j=["MSXML2.DOMDocument.6.0","MSXML2.DOMDocument.5.0","MSXML2.DOMDocument.4.0","MSXML2.DOMDocument.3.0","MSXML2.DOMDocument","Microsoft.XMLDOM"],k=0;k<j.length;k++)try{f=new ActiveXObject(j[k]);break}catch(l){}if(f.parseError.reason)return null;f.async=false;i==0?f.loadXML(c):f.load(c)}else if(document.implementation&&document.implementation.createDocument){f=document.implementation.createDocument("",
"",null);if(i){f.async=false;f.load(c)}else f=(new DOMParser).parseFromString(c,"text/xml");if(f.documentElement.nodeName=="parsererror")return null}return f.documentElement},doCopy:function(c){if(window.clipboardData)window.clipboardData.setData("Text",c);else if(navigator.userAgent.indexOf("Opera")!=-1)window.location=c;else{try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect")}catch(h){alert("\u60a8\u7684\u5f53\u524d\u6d4f\u89c8\u5668\u8bbe\u7f6e\u5df2\u5173\u95ed\u6b64\u529f\u80fd\uff01\u8bf7\u6309\u4ee5\u4e0b\u6b65\u9aa4\u5f00\u542f\u6b64\u529f\u80fd\uff01\n\u65b0\u5f00\u4e00\u4e2a\u6d4f\u89c8\u5668\uff0c\u5728\u6d4f\u89c8\u5668\u5730\u5740\u680f\u8f93\u5165'about:config'\u5e76\u56de\u8f66\u3002\n\u7136\u540e\u627e\u5230'signed.applets.codebase_principal_support'\u9879\uff0c\u53cc\u51fb\u540e\u8bbe\u7f6e\u4e3a'true'\u3002\n\u58f0\u660e\uff1a\u672c\u529f\u80fd\u4e0d\u4f1a\u5371\u6781\u60a8\u8ba1\u7b97\u673a\u6216\u6570\u636e\u7684\u5b89\u5168\uff01")}var f=
Components.classes["@mozilla.org/widget/clipboard;1"].createInstance(Components.interfaces.nsIClipboard);if(f){var i=Components.classes["@mozilla.org/widget/transferable;1"].createInstance(Components.interfaces.nsITransferable);if(i){i.addDataFlavor("text/unicode");var j={};j=Components.classes["@mozilla.org/supports-string;1"].createInstance(Components.interfaces.nsISupportsString);j.data=c;i.setTransferData("text/unicode",j,c.length*2);f.setData(i,null,Components.interfaces.nsIClipboard.kGlobalClipboard)}}}},
addCSSRule:function(c,h,f){var i=document.styleSheets[document.styleSheets.length-1];if(f<0||YH.isEmpty(f))f=(i.rules||i.cssRules).length;i.cssRules?i.insertRule(c+"{"+h+"}",f):i.addRule(c,h,f)},console:function(c){window.console&&console.log(c)},QueryString:function(c){return location.href.getQueryString(c)}});if(YH.isIE6)try{document.execCommand("BackgroundImageCache",false,true)}catch(g){}a.cookie=function(c,h,f){if(arguments.length>1&&(h===null||typeof h!=="object")){f=jQuery.extend({},f);if(h===
null)f.expires=-1;if(typeof f.expires==="number"){var i=f.expires,j=f.expires=new Date;j.setDate(j.getDate()+i)}return document.cookie=[encodeURIComponent(c),"=",f.raw?String(h):encodeURIComponent(String(h)),f.expires?"; expires="+f.expires.toUTCString():"",f.path?"; path="+f.path:"",f.domain?"; domain="+f.domain:"",f.secure?"; secure":""].join("")}f=h||{};j=f.raw?function(k){return k}:decodeURIComponent;return(i=RegExp("(?:^|; )"+encodeURIComponent(c)+"=([^;]*)").exec(document.cookie))?j(i[1]):null}})(jQuery);
YH.applyIf(String,{leftPad:function(a,b,d){a=String(a)||"";for(d||(d=" ");a.length<b;)a=d+a;return a},cut:function(a,b,d){a+="";d=d||"";for(var e=a.length,g=Math.min(Math.floor(b/2),e),c=String.getRealLen(a.slice(0,g));g<e&&c<b;g++)c+=1+!/[\x00-\xFF]/.test(a.charAt(g));return a.slice(0,c>b?g-1:g)+(g<e?d:"")},getRealLen:function(a,b){if(typeof a!="string")return 0;if(b){var d=a.replace(/[\x00-\xFF]/g,"");return a.length-d.length+encodeURI(d).length/3}else return a.replace(/[^\x00-\xFF]/g,"**").length},
isUrl:function(a){return/^(?:ht|f)tp(?:s)?\:\/\/(?:[\w\-\.]+)\.\w+/i.test(a)},compareVersions:function(a,b){for(var d=a.split("."),e=b.split("."),g=Math.max(d.length,e.length),c=0,h=0;c==0&&h<g;h++){var f=d[h]||"",i=e[h]||"",j=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var l=j.exec(f)||["","",""],m=k.exec(i)||["","",""];if(l[0].length==0&&m[0].length==0)break;c=l[1].length==0?0:parseInt(l[1],10);var n=m[1].length==0?0:parseInt(m[1],10);c=String.compareElements(c,n)||String.compareElements(l[2].length==
0,m[2].length==0)||String.compareElements(l[2],m[2])}while(c==0)}return c},compareElements:function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}});YH.applyIf(String.prototype,{getQueryString:function(a){if(a=this.match(RegExp("(^|&|\\?)"+a+"=([^&]*)(&|$)")))return unescape(a[2]);return null},compileTpl:function(a){return this.replace(/\{\w+\}/g,function(b){return a[b.replace(/\{|\}/g,"")]||""})}});
YH.applyIf(Array.prototype,{unique:function(){var a={},b=[];$.each(this,function(d,e){a[e]||b.push(e);a[e]=true});return b},indexOf:function(a){for(var b=0,d=this.length;b<d;b++)if(this[b]==a)return b;return-1},remove:function(a){a=this.indexOf(a);a!=-1&&this.splice(a,1);return this}});
YH.dom={fixedPosition:function(){if(YH.isIE6){document.body.style.height="100%";document.body.style.overflow="auto";YH.addCSSRule("*html","overflow-x:auto;overflow-y:hidden;")}},elemFixedPos:function(a){$(a).css("position",YH.isIE6?"absolute":"fixed")},getDocumentWindow:function(a){a=a||document;return a.parentWindow||a.defaultView},getDocumentWidth:function(a){return $(a||document).width()},getDocumentHeight:function(a){return $(a||document).height()},getViewportWidth:function(a){return $(a||window).width()},
getViewportHeight:function(a){return $(a||window).height()},getRegion:function(a,b){var d=document;if(b)d=b.document;var e=YH.$id(a);d=$(e==d||e==d.body?d.body:e).offset();return{top:d.top,right:d.left+e.offsetWidth,bottom:d.top+e.offsetHeight,left:d.left}},getMouseX:function(a){return a.pageX||a.clientX+YH.root().scrollLeft},getMouseY:function(a){return a.pageY||a.clientY+YH.root().scrollTop},scrollintoContainer:function(a,b,d,e,g){var c=$(a).offset(),h=$(b).offset(),f=YH.$id(a);a=YH.$id(b);var i=
c.left-h.left;c=c.top-h.top;h=a.clientWidth-f.offsetWidth;f=a.clientHeight-f.offsetHeight;if(d){d=a.scrollLeft+i-h/2;i=a.scrollTop+c-f/2}else{d=a.scrollLeft+Math.min(i,Math.max(i-h,0));i=a.scrollTop+Math.min(c,Math.max(c-f,0))}if(e)b.stop().animate({scrollLeft:g&&g.noL?a.scrollLeft:d,scrollTop:i},$.extend({duration:"slow"},g||{}));else{a.scrollLeft=d;a.scrollTop=i}},Bound:function(a,b,d,e,g,c,h){for(var f=window;f.parent!=f;)f=f.parent;var i=YH.dom.getViewportWidth(f)-10,j=YH.dom.getViewportHeight(f)-
10,k,l;l=k=false;var m=$(h||document).scrollLeft()+5,n=$(h||document).scrollTop()+5;h=$(a).outerWidth();a=$(a).outerHeight();b=YH.dom.getRegion(b,f);if(g||c){k=g.charAt(0);g=g.charAt(g.length-1);l=c.charAt(0);c=c.charAt(c.length-1);k=k=="t"&&l=="b"||k=="b"&&l=="t";l=g=="r"&&c=="l"||g=="l"&&c=="r"}if(d+h>i+m)d=l?b.left-h:i+m-h;if(d<m)d=l?b.right:m;if(e+a>j+n)e=k?b.top-a:j+n-a;if(e<n)e=k?b.bottom:n;return[d,e]},getScrollbarWidth:function(){var a=$("<div/>").css({visibility:"hidden",overflow:"scroll",
position:"absolute",top:"0",width:"100px",height:"100px"}).appendTo(document.body),b=a[0].offsetWidth-a[0].clientWidth;a.remove();return b}};
(function(a){a.fn.getAlignToXY=function(b,d,e,g){e=e||[0,0];d=(!d||d=="?"?"tl-bl?":!/-/.test(d)&&d!==""?"tl-"+d:d||"tl-bl").toLowerCase();var c,h,f=false;if(d=d.match(/^([a-z]+)-([a-z]+)(\?)?$/)){var i=d[1],j=d[2];f=!!d[3];c=a(this).getAnchorXY(i,true,g);h=a(b).getAnchorXY(j,false,g);d=h[0]-c[0]+e[0];e=h[1]-c[1]+e[1];if(f){b=YH.dom.Bound(this,b,d,e,i,j,g);d=b[0];e=b[1]}return{x:d,y:e}}};a.fn.getAnchorXY=function(b,d,e){b=(b||"tl").toLowerCase();for(var g=window;g.parent!=g;)g=g.parent;var c=YH.$id(this)==
(e||document).body||YH.$id(this)==(e||document),h=c?YH.dom.getViewportWidth(g):a(this).outerWidth();g=c?YH.dom.getViewportHeight(g):a(this).outerHeight();var f=Math.round,i=this;if(c)i=(e||document).body;i=a(i).offset();e=c?a(this).scrollLeft():!d?i.left:0;d=c?a(this).scrollTop():!d?i.top:0;b={c:[f(h*0.5),f(g*0.5)],t:[f(h*0.5),0],l:[0,f(g*0.5)],r:[h,f(g*0.5)],b:[f(h*0.5),g],tl:[0,0],bl:[0,g],br:[h,g],tr:[h,0]}[b];return[b[0]+e,b[1]+d]};a.fn.unselectable=function(){return this.attr("unselectable",
"on").css("MozUserSelect","none").bind("selectstart",function(){return false})};a.fn.setInlineBlock=function(){return this.each(function(){a(this).css("position","relative");if(YH.userAgent.isIE&&!YH.userAgent.isVersion("8"))a(this).css({zoom:"1",display:"inline"});else YH.userAgent.isGecko?a(this).css("display",YH.userAgent.isVersion("1.9a")?"inline-block":"-moz-inline-box"):a(this).css("display","inline-block")})};a.fn.setOpacity=function(b){var d=a(this)[0].style;if("opacity"in d)d.opacity=b;else if("MozOpacity"in
d)d.MozOpacity=b;else if("filter"in d)d.filter=b===""?"":"alpha(opacity="+b*100+")"};a.fn.createProxy=function(b,d){var e=a("<div/>").attr("id",b.id?b.id:YH.genId("proxy")).addClass(b.cls);b.html&&e.html(b.html);d?e.appendTo(d):e.insertBefore(a(this));return e};a.fn.EpCp=function(b){function d(c,h){var f=h=="cp"?e.img_collapse:e.img_expand;if(c.attr("src"))c.attr("src",f);else if(c.children("img")[0])c.children("img").attr("src",f);else h=="cp"?c.addClass(e.clsCp).removeClass(e.clsEp):c.addClass(e.clsEp).removeClass(e.clsCp)}
var e=a.extend({img_expand:YH.furl+"Marketing/ico15.jpg",img_collapse:YH.furl+"Marketing/ico14.jpg",clsEp:"clsEp",clsCp:"clsCp"},b||{}),g=this;return this.each(function(){var c=a(this),h=c.attr("tog");c.click(function(){cls=c.attr("src")?false:true;switch(h){case "epall":a(g).each(function(){var i=a(this);if(i.attr("tog")!=h){d(i,"cp");a("#"+i.attr("tog")).show()}});break;case "cpall":a(g).each(function(){var i=a(this);if(i.attr("tog")!=h){d(i,"ep");a("#"+i.attr("tog")).hide()}});break;default:var f=
a("#"+h);if(f.css("display")=="none"){d(c,"cp");f.show()}else{f.hide();d(c,"ep")}}})})};a.fn.dropdownmenu=function(b){b=a.extend({target:false},b);return this.each(function(){var d=a(this),e=a(b.target);a(d).click(function(){window.last_dropdown_target&&a(window.last_dropdown_target).hide();window.last_dropdown_target=e;a(e).slideDown("fast").show();typeof b.cb=="function"&&b.cb();setTimeout(function(){a(e).find("select").click(function(){return false});a(e).one("click",function(){return false});
a("body").one("click",function(){a(e).hide()})},300);return false})})};a.fLayer=function(b,d){this.opt={title:null,doc:window.self.document,relat:true,animated:false,onShow:function(){}};this.mm=b;this.dc=this.dt=null;this.opt=a.extend(this.opt,d||{});this.render()};a.fLayer.prototype={render:function(){var b=this.opt,d=a(this.mm),e=this;this.layer=a('<div style="background-color:#fff;width:300px;border:1px solid #ccc;position:absolute;margin:0;padding:0" class="flayer"><div class="flayer-bar" style="position:relative">'+
(this.opt.title?'<div class="flayer-title" style="text-align:left;background:#eee;padding:2px 5px">'+this.opt.title+"</div>":"")+'<span class="flayer-close" style="position:absolute;width:15px;height:15px;top:2px;right:2px;cursor:pointer;color:#f00"><img src="'+YH.furl+'Projects/ico-close.png" alt="\u5173\u95ed" /></span></div><div class="flayer-content" style="margin:0px;padding:5px;white-space:normal;word-break:break-all;overflow:hidden;text-align:left"></div></div>');this.layer.appendTo(d,b.doc).hide();
b.cls&&this.layer.addClass(b.cls);d=d.offset();b.relat&&this.layer.css({left:d.left,top:d.top});this.dt=this.layer.find(".flayer-title");this.dc=this.layer.find(".flayer-content");b.width&&this.layer.css("width",b.width);b.height&&this.layer.css("height",b.height);a(this.mm).data("ly",this);b.animated?e.layer.slideDown("slow"):e.layer.show();b.onShow.call(this);a(".flayer-close",e.layer).click(function(g){g.stopPropagation();b.animated?e.layer.slideUp("slow").hide():e.layer.hide()});return this},
setTitle:function(b){this.dt.html(b)},setContent:function(b){this.dc.html(b)},show:function(){this.layer.show()},hide:function(){this.layer.hide()},destroy:function(){a(this.mm).removeData("ly");this.layer.remove()}};a.fn.fLayer=function(b){var d=a(this).data("ly");if(d){d.show();return d}return new a.fLayer(this,b)};a.tmsg=function(b,d,e){var g=e||{},c=["gtl_ico_hits","gtl_ico_succ","gtl_ico_fail","gtl_ico_wait"];e=g.time_out?parseInt(g.time_out,10):3E3;b=b?b:"a3_wait";var h=YH.$id(b),f=g.zindex||
2E4,i=g.pos?g.pos:"c-c",j;c=c[g.infotype?g.infotype>3&&g.infotype<0?0:g.infotype:0];var k=g.offsets?g.offsets:null;h||(h=a('<div id="'+b+'" class="qz_msgbox_layer_wrap"><span class="qz_msgbox_layer"><span class="msg-ct">\u4fdd\u5b58</span><span class="gtl_ico"></span><span class="gtl_end"></span></span></div>').css({display:"block",position:"absolute",zIndex:f}).appendTo(document.body));j=a(h);j.find("span.gtl_ico").removeClass("gtl_ico_hits gtl_ico_succ gtl_ico_fail gtl_ico_wait").addClass(c);j.find("span.msg-ct").html(d);
d=j.getAlignToXY(g.el||document,i,k);j.css({left:d.x,top:d.y}).show();g.notime||window.setTimeout(function(){j[0].style.display="none";g.callback&&typeof g.callback=="function"&&g.callback()},e)};a.fn.mask=function(b){a(this).each(function(){a.maskElement(a(this),b)})};a.fn.unmask=function(){a(this).each(function(){a.unmaskElement(a(this))})};a.fn.isMasked=function(){return this.hasClass("masked")};a.maskElement=function(b,d){var e=b.data("_mask_id"),g=9999,c=b.css("position");if(!e){e=YH.genId("mask_");
b.data("_mask_id",e)}if(c=="absolute")g=b.css("zIndex");if(c=="static"){b.css("position","relative");b.data("_mask_chgpos","static")}b.isMasked()&&a.unmaskElement(b);b.addClass("masked");c=a('<div id="'+e+'" class="loadmask" style="z-index:'+(g+5)+';position:absolute;top:0;left:0;background-color:#CCC;width:100%;height:100%;zoom:1;">'+(YH.isIE6?'<iframe hideFocus="true" frameborder="0" src="javascript:\'\'" style="position:absolute;z-index:-1;width:100%;height:100%;top:0px;left:0px;filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0)"></iframe>':
"")+"</div>");c.setOpacity(0.5);if(YH.userAgent.isIE){c.height(b.height()+parseInt(b.css("padding-top"))+parseInt(b.css("padding-bottom")));c.width(b.width()+parseInt(b.css("padding-left"))+parseInt(b.css("padding-right")))}b.append(c);if(d!==undefined){var h=b.offset().top;c=b.height();var f=a(document).scrollTop(),i=YH.dom.getViewportHeight();if(h>=f&&h+c<=f+i){e=a('<div id="'+(e+"_msg")+'" style="display:none;z-index:'+(g+6)+';position:absolute;top:0;left:0;" class="qz_msgbox_layer_wrap"><span class="qz_msgbox_layer">'+
d+'<span class="gtl_ico_wait"></span><span class="gtl_end"></span></span></div>');b.append(e);g=Math.round(c/2-(e.height()-parseInt(e.css("padding-top"))-parseInt(e.css("padding-bottom")))/2);e.css("top",g+"px");e.css("left",Math.round(b.width()/2-(e.width()-parseInt(e.css("padding-left"))-parseInt(e.css("padding-right")))/2)+"px");e.show()}else a.tmsg(e+"_msg",d,{notime:true,zindex:g+6,infotype:3})}};a.unmaskElement=function(b){var d=b.data("_mask_id"),e=b.data("_mask_chgpos");b.find("#"+d).remove();
a("#"+d+"_msg")[0]&&a("#"+d+"_msg").remove();b.removeClass("masked");if(e){b.css("position",e);b.removeData("_mask_chgpos")}}})(jQuery);
