/*
Copyright 2011, A+ v1.0.0
build time: Aug 16 11:59
*/
(function(){function l(){if(l.is(arguments[0],X)){for(var a=arguments[0],b=Fa[C](l,a.splice(0,3+l.is(a[0],N))),c=b.set(),e=0,f=a[q];e<f;e++){var d=a[e]||{};ha[t](d.type)&&c[F](b[d.type]().attr(d))}return c}return Fa[C](l,arguments)}function Z(){for(var a=[],b=0;b<32;b++)a[b]=(~~(y.random()*16))[da](16);a[12]=4;a[16]=(a[16]&3|8)[da](16);return"r-"+a[O]("")}function J(a,b,c){function e(){var f=Array[z].slice.call(arguments,0),d=f[O]("\u25ba"),g=e.cache=e.cache||{},j=e.count=e.count||[];if(g[t](d))return c?
c(g[d]):g[d];j[q]>=1E3&&delete g[j.shift()];j[F](d);g[d]=a[C](b,f);return c?c(g[d]):g[d]}return e}function V(){return this.x+L+this.y}function fa(a){return function(b,c,e,f){var d={back:a};l.is(e,"function")?f=e:d.rot=e;b&&b.constructor==D&&(b=b.attrs.path);b&&(d.along=b);return this.animate(d,c,f)}}function ea(a,b,c,e,f,d){function g(p,w){var r,o,s,H;s=p;for(o=0;o<8;o++){H=((i*s+h)*s+j)*s-p;if(M(H)<w)return s;r=(3*i*s+2*h)*s+j;if(M(r)<1.0E-6)break;s-=H/r}r=0;o=1;s=p;if(s<r)return r;if(s>o)return o;
for(;r<o;){H=((i*s+h)*s+j)*s;if(M(H-p)<w)break;if(p>H)r=s;else o=s;s=(o-r)/2+r}return s}var j=3*b,h=3*(e-b)-j,i=1-j-h,k=3*c,m=3*(f-c)-k,n=1-k-m;return function(p,w){var r=g(p,w);return((n*r+m)*r+k)*r}(a,1/(200*d))}l.version="1.5.2";var R=/[, ]+/,ha={circle:1,rect:1,path:1,ellipse:1,text:1,image:1},na=/\{(\d+)\}/g,z="prototype",t="hasOwnProperty",v=document,K=window,ka={was:Object[z][t].call(K,"Raphael"),is:K.Raphael},la=function(){this.customAttributes={}},E,C="apply",oa="createTouch"in v,L=" ",A=
String,pa="click dblclick mousedown mousemove mouseout mouseover mouseup touchstart touchmove touchend orientationchange touchcancel gesturestart gesturechange gestureend".split(L),Ga={mousedown:"touchstart",mousemove:"touchmove",mouseup:"touchend"},O="join",q="length",ja=A[z].toLowerCase,y=Math,W=y.max,ca=y.min,M=y.abs,G=y.pow,S=y.PI,N="number",X="array",da="toString",ob=Object[z][da],F="push",Sa=/^url\(['"]?([^\)]+?)['"]?\)$/i,pb=/^\s*((#[a-f\d]{6})|(#[a-f\d]{3})|rgba?\(\s*([\d\.]+%?\s*,\s*[\d\.]+%?\s*,\s*[\d\.]+(?:%?\s*,\s*[\d\.]+)?)%?\s*\)|hsba?\(\s*([\d\.]+(?:deg|\xb0|%)?\s*,\s*[\d\.]+%?\s*,\s*[\d\.]+(?:%?\s*,\s*[\d\.]+)?)%?\s*\)|hsla?\(\s*([\d\.]+(?:deg|\xb0|%)?\s*,\s*[\d\.]+%?\s*,\s*[\d\.]+(?:%?\s*,\s*[\d\.]+)?)%?\s*\))\s*$/i,
qb={NaN:1,Infinity:1,"-Infinity":1},rb=/^(?:cubic-)?bezier\(([^,]+),([^,]+),([^,]+),([^\)]+)\)/,P=y.round,x=parseFloat,ga=parseInt,va=A[z].toUpperCase,wa={blur:0,"clip-rect":"0 0 1e9 1e9",cursor:"default",cx:0,cy:0,fill:"#fff","fill-opacity":1,font:'10px "Arial"',"font-family":'"Arial"',"font-size":"10","font-style":"normal","font-weight":400,gradient:0,height:0,href:"http://raphaeljs.com/",opacity:1,path:"M0,0",r:0,rotation:0,rx:0,ry:0,scale:"1 1",src:"",stroke:"#000","stroke-dasharray":"","stroke-linecap":"butt",
"stroke-linejoin":"butt","stroke-miterlimit":0,"stroke-opacity":1,"stroke-width":1,target:"_blank","text-anchor":"middle",title:"Raphael",translation:"0 0",width:0,x:0,y:0},Ha={along:"along",blur:N,"clip-rect":"csv",cx:N,cy:N,fill:"colour","fill-opacity":N,"font-size":N,height:N,opacity:N,path:"path",r:N,rotation:"csv",rx:N,ry:N,scale:"csv",stroke:"colour","stroke-opacity":N,"stroke-width":N,translation:"csv",width:N,x:N,y:N},sb=/^(from|to|\d+%?)$/,Ia=/\s*,\s*/,tb={hs:1,rg:1},ub=/,?([achlmqrstvxz]),?/gi,
vb=/([achlmqstvz])[\s,]*((-?\d*\.?\d*(?:e[-+]?\d+)?\s*,?\s*)+)/ig,wb=/(-?\d*\.?\d*(?:e[-+]?\d+)?)\s*,?\s*/ig,Ta=/^r(?:\(([^,]+?)\s*,\s*([^\)]+?)\))?/,xb=function(a,b){return a.key-b.key};l.type=K.SVGAngle||v.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")?"SVG":"VML";if(l.type=="VML"){var $=v.createElement("div");$.innerHTML='<v:shape adj="1"/>';$=$.firstChild;$.style.behavior="url(#default#VML)";if(!($&&typeof $.adj=="object"))return l.type=null;$=null}l.svg=
!(l.vml=l.type=="VML");la[z]=l[z];E=la[z];l._id=0;l._oid=0;l.fn={};l.is=function(a,b){b=ja.call(b);if(b=="finite")return!qb[t](+a);return b=="null"&&a===null||b==typeof a||b=="object"&&a===Object(a)||b=="array"&&Array.isArray&&Array.isArray(a)||ob.call(a).slice(8,-1).toLowerCase()==b};l.angle=function(a,b,c,e,f,d){if(f==null){a-=c;b-=e;if(!a&&!b)return 0;return((a<0)*180+y.atan(-b/-a)*180/S+360)%360}else return l.angle(a,b,f,d)-l.angle(c,e,f,d)};l.rad=function(a){return a%360*S/180};l.deg=function(a){return a*
180/S%360};l.snapTo=function(a,b,c){c=l.is(c,"finite")?c:10;if(l.is(a,X))for(var e=a.length;e--;){if(M(a[e]-b)<=c)return a[e]}else{a=+a;e=b%a;if(e<c)return b-e;if(e>a-c)return b-e+a}return b};l.setWindow=function(a){K=a;v=K.document};var xa=function(a){if(l.vml){var b=/^\s+|\s+$/g,c;try{var e=new ActiveXObject("htmlfile");e.write("<body>");e.close();c=e.body}catch(f){c=createPopup().document.body}var d=c.createTextRange();xa=J(function(j){try{c.style.color=A(j).replace(b,"");var h=d.queryCommandValue("ForeColor");
return"#"+("000000"+((h&255)<<16|h&65280|(h&16711680)>>>16)[da](16)).slice(-6)}catch(i){return"none"}})}else{var g=v.createElement("i");g.title="Rapha\u00ebl Colour Picker";g.style.display="none";v.body.appendChild(g);xa=J(function(j){g.style.color=j;return v.defaultView.getComputedStyle(g,"").getPropertyValue("color")})}return xa(a)},Ua=function(){return"hsb("+[this.h,this.s,this.b]+")"},yb=function(){return"hsl("+[this.h,this.s,this.l]+")"},zb=function(){return this.hex};l.hsb2rgb=function(a,b,c,e){if(l.is(a,
"object")&&"h"in a&&"s"in a&&"b"in a){c=a.b;b=a.s;a=a.h;e=a.o}return l.hsl2rgb(a,b,c/2,e)};l.hsl2rgb=function(a,b,c,e){if(l.is(a,"object")&&"h"in a&&"s"in a&&"l"in a){c=a.l;b=a.s;a=a.h}if(a>1||b>1||c>1){a/=360;b/=100;c/=100}var f={},d=["r","g","b"],g;if(b){b=c<0.5?c*(1+b):c+b-c*b;c=2*c-b;for(var j=0;j<3;j++){g=a+1/3*-(j-1);g<0&&g++;g>1&&g--;f[d[j]]=g*6<1?c+(b-c)*6*g:g*2<1?b:g*3<2?c+(b-c)*(2/3-g)*6:c}}else f={r:c,g:c,b:c};f.r*=255;f.g*=255;f.b*=255;f.hex="#"+(16777216|f.b|f.g<<8|f.r<<16).toString(16).slice(1);
l.is(e,"finite")&&(f.opacity=e);f.toString=zb;return f};l.rgb2hsb=function(a,b,c){if(b==null&&l.is(a,"object")&&"r"in a&&"g"in a&&"b"in a){c=a.b;b=a.g;a=a.r}if(b==null&&l.is(a,"string")){var e=l.getRGB(a);a=e.r;b=e.g;c=e.b}if(a>1||b>1||c>1){a/=255;b/=255;c/=255}e=W(a,b,c);var f=ca(a,b,c);if(f==e)return{h:0,s:0,b:e,toString:Ua};else{f=e-f;a=a==e?(b-c)/f:b==e?2+(c-a)/f:4+(a-b)/f;a/=6;a<0&&a++;a>1&&a--}return{h:a,s:f/e,b:e,toString:Ua}};l.rgb2hsl=function(a,b,c){if(b==null&&l.is(a,"object")&&"r"in a&&
"g"in a&&"b"in a){c=a.b;b=a.g;a=a.r}if(b==null&&l.is(a,"string")){var e=l.getRGB(a);a=e.r;b=e.g;c=e.b}if(a>1||b>1||c>1){a/=255;b/=255;c/=255}e=W(a,b,c);var f=ca(a,b,c),d=(e+f)/2;if(f==e)a={h:0,s:0,l:d};else{var g=e-f;a=a==e?(b-c)/g:b==e?2+(c-a)/g:4+(a-b)/g;a/=6;a<0&&a++;a>1&&a--;a={h:a,s:d<0.5?g/(e+f):g/(2-e-f),l:d}}a.toString=yb;return a};l._path2string=function(){return this.join(",").replace(ub,"$1")};l.getRGB=J(function(a){if(!a||(a=A(a)).indexOf("-")+1)return{r:-1,g:-1,b:-1,hex:"none",error:1};
if(a=="none")return{r:-1,g:-1,b:-1,hex:"none"};!(tb[t](a.toLowerCase().substring(0,2))||a.charAt()=="#")&&(a=xa(a));var b,c,e,f,d;if(a=a.match(pb)){if(a[2]){e=ga(a[2].substring(5),16);c=ga(a[2].substring(3,5),16);b=ga(a[2].substring(1,3),16)}if(a[3]){e=ga((d=a[3].charAt(3))+d,16);c=ga((d=a[3].charAt(2))+d,16);b=ga((d=a[3].charAt(1))+d,16)}if(a[4]){d=a[4].split(Ia);b=x(d[0]);d[0].slice(-1)=="%"&&(b*=2.55);c=x(d[1]);d[1].slice(-1)=="%"&&(c*=2.55);e=x(d[2]);d[2].slice(-1)=="%"&&(e*=2.55);a[1].toLowerCase().slice(0,
4)=="rgba"&&(f=x(d[3]));d[3]&&d[3].slice(-1)=="%"&&(f/=100)}if(a[5]){d=a[5].split(Ia);b=x(d[0]);d[0].slice(-1)=="%"&&(b*=2.55);c=x(d[1]);d[1].slice(-1)=="%"&&(c*=2.55);e=x(d[2]);d[2].slice(-1)=="%"&&(e*=2.55);(d[0].slice(-3)=="deg"||d[0].slice(-1)=="\u00b0")&&(b/=360);a[1].toLowerCase().slice(0,4)=="hsba"&&(f=x(d[3]));d[3]&&d[3].slice(-1)=="%"&&(f/=100);return l.hsb2rgb(b,c,e,f)}if(a[6]){d=a[6].split(Ia);b=x(d[0]);d[0].slice(-1)=="%"&&(b*=2.55);c=x(d[1]);d[1].slice(-1)=="%"&&(c*=2.55);e=x(d[2]);d[2].slice(-1)==
"%"&&(e*=2.55);(d[0].slice(-3)=="deg"||d[0].slice(-1)=="\u00b0")&&(b/=360);a[1].toLowerCase().slice(0,4)=="hsla"&&(f=x(d[3]));d[3]&&d[3].slice(-1)=="%"&&(f/=100);return l.hsl2rgb(b,c,e,f)}a={r:b,g:c,b:e};a.hex="#"+(16777216|e|c<<8|b<<16).toString(16).slice(1);l.is(f,"finite")&&(a.opacity=f);return a}return{r:-1,g:-1,b:-1,hex:"none",error:1}},l);l.getColor=function(a){a=this.getColor.start=this.getColor.start||{h:0,s:1,b:a||0.75};var b=this.hsb2rgb(a.h,a.s,a.b);a.h+=0.075;if(a.h>1){a.h=0;a.s-=0.2;a.s<=
0&&(this.getColor.start={h:0,s:1,b:a.b})}return b.hex};l.getColor.reset=function(){delete this.start};l.parsePathString=J(function(a){if(!a)return null;var b={a:7,c:6,h:1,l:2,m:2,q:4,s:4,t:2,v:1,z:0},c=[];if(l.is(a,X)&&l.is(a[0],X))c=ya(a);c[q]||A(a).replace(vb,function(e,f,d){var g=[];e=ja.call(f);d.replace(wb,function(j,h){h&&g[F](+h)});if(e=="m"&&g[q]>2){c[F]([f].concat(g.splice(0,2)));e="l";f=f=="m"?"l":"L"}for(;g[q]>=b[e];){c[F]([f].concat(g.splice(0,b[e])));if(!b[e])break}});c[da]=l._path2string;
return c});l.findDotsAtSegment=function(a,b,c,e,f,d,g,j,h){var i=1-h,k=G(i,3)*a+G(i,2)*3*h*c+i*3*h*h*f+G(h,3)*g;i=G(i,3)*b+G(i,2)*3*h*e+i*3*h*h*d+G(h,3)*j;var m=a+2*h*(c-a)+h*h*(f-2*c+a),n=b+2*h*(e-b)+h*h*(d-2*e+b),p=c+2*h*(f-c)+h*h*(g-2*f+c),w=e+2*h*(d-e)+h*h*(j-2*d+e);a=(1-h)*a+h*c;b=(1-h)*b+h*e;f=(1-h)*f+h*g;d=(1-h)*d+h*j;j=90-y.atan((m-p)/(n-w))*180/S;(m>p||n<w)&&(j+=180);return{x:k,y:i,m:{x:m,y:n},n:{x:p,y:w},start:{x:a,y:b},end:{x:f,y:d},alpha:j}};var Aa=J(function(a){if(!a)return{x:0,y:0,width:0,
height:0};a=za(a);for(var b=0,c=0,e=[],f=[],d,g=0,j=a[q];g<j;g++){d=a[g];if(d[0]=="M"){b=d[1];c=d[2];e[F](b);f[F](c)}else{b=Ab(b,c,d[1],d[2],d[3],d[4],d[5],d[6]);e=e.concat(b.min.x,b.max.x);f=f.concat(b.min.y,b.max.y);b=d[5];c=d[6]}}a=ca[C](0,e);d=ca[C](0,f);return{x:a,y:d,width:W[C](0,e)-a,height:W[C](0,f)-d}}),ya=function(a){var b=[];if(!l.is(a,X)||!l.is(a&&a[0],X))a=l.parsePathString(a);for(var c=0,e=a[q];c<e;c++){b[c]=[];for(var f=0,d=a[c][q];f<d;f++)b[c][f]=a[c][f]}b[da]=l._path2string;return b},
Ja=J(function(a){if(!l.is(a,X)||!l.is(a&&a[0],X))a=l.parsePathString(a);var b=[],c=0,e=0,f=0,d=0,g=0;if(a[0][0]=="M"){c=a[0][1];e=a[0][2];f=c;d=e;g++;b[F](["M",c,e])}for(var j=a[q];g<j;g++){var h=b[g]=[],i=a[g];if(i[0]!=ja.call(i[0])){h[0]=ja.call(i[0]);switch(h[0]){case "a":h[1]=i[1];h[2]=i[2];h[3]=i[3];h[4]=i[4];h[5]=i[5];h[6]=+(i[6]-c).toFixed(3);h[7]=+(i[7]-e).toFixed(3);break;case "v":h[1]=+(i[1]-e).toFixed(3);break;case "m":f=i[1];d=i[2];default:for(var k=1,m=i[q];k<m;k++)h[k]=+(i[k]-(k%2?c:
e)).toFixed(3)}}else{b[g]=[];if(i[0]=="m"){f=i[1]+c;d=i[2]+e}h=0;for(k=i[q];h<k;h++)b[g][h]=i[h]}i=b[g][q];switch(b[g][0]){case "z":c=f;e=d;break;case "h":c+=+b[g][i-1];break;case "v":e+=+b[g][i-1];break;default:c+=+b[g][i-2];e+=+b[g][i-1]}}b[da]=l._path2string;return b},0,ya),ra=J(function(a){if(!l.is(a,X)||!l.is(a&&a[0],X))a=l.parsePathString(a);var b=[],c=0,e=0,f=0,d=0,g=0;if(a[0][0]=="M"){c=+a[0][1];e=+a[0][2];f=c;d=e;g++;b[0]=["M",c,e]}for(var j=a[q];g<j;g++){var h=b[g]=[],i=a[g];if(i[0]!=va.call(i[0])){h[0]=
va.call(i[0]);switch(h[0]){case "A":h[1]=i[1];h[2]=i[2];h[3]=i[3];h[4]=i[4];h[5]=i[5];h[6]=+(i[6]+c);h[7]=+(i[7]+e);break;case "V":h[1]=+i[1]+e;break;case "H":h[1]=+i[1]+c;break;case "M":f=+i[1]+c;d=+i[2]+e;default:for(var k=1,m=i[q];k<m;k++)h[k]=+i[k]+(k%2?c:e)}}else{k=0;for(m=i[q];k<m;k++)b[g][k]=i[k]}switch(h[0]){case "Z":c=f;e=d;break;case "H":c=h[1];break;case "V":e=h[1];break;case "M":f=b[g][b[g][q]-2];d=b[g][b[g][q]-1];default:c=b[g][b[g][q]-2];e=b[g][b[g][q]-1]}}b[da]=l._path2string;return b},
null,ya),Va=function(a,b,c,e,f,d){var g=1/3,j=2/3;return[g*a+j*c,g*b+j*e,g*f+j*c,g*d+j*e,f,d]},Wa=function(a,b,c,e,f,d,g,j,h,i){var k=S*120/180,m=S/180*(+f||0),n=[],p,w=J(function(Q,T,I){var ma=Q*y.cos(I)-T*y.sin(I);Q=Q*y.sin(I)+T*y.cos(I);return{x:ma,y:Q}});if(i){s=i[0];p=i[1];d=i[2];o=i[3]}else{p=w(a,b,-m);a=p.x;b=p.y;p=w(j,h,-m);j=p.x;h=p.y;y.cos(S/180*f);y.sin(S/180*f);p=(a-j)/2;s=(b-h)/2;o=p*p/(c*c)+s*s/(e*e);if(o>1){o=y.sqrt(o);c*=o;e*=o}o=c*c;var r=e*e;o=(d==g?-1:1)*y.sqrt(M((o*r-o*s*s-r*p*
p)/(o*s*s+r*p*p)));d=o*c*s/e+(a+j)/2;var o=o*-e*p/c+(b+h)/2,s=y.asin(((b-o)/e).toFixed(9));p=y.asin(((h-o)/e).toFixed(9));s=a<d?S-s:s;p=j<d?S-p:p;s<0&&(s=S*2+s);p<0&&(p=S*2+p);if(g&&s>p)s-=S*2;if(!g&&p>s)p-=S*2}if(M(p-s)>k){n=p;r=j;var H=h;p=s+k*(g&&p>s?1:-1);j=d+c*y.cos(p);h=o+e*y.sin(p);n=Wa(j,h,c,e,f,0,g,r,H,[p,n,d,o])}d=p-s;f=y.cos(s);k=y.sin(s);g=y.cos(p);p=y.sin(p);d=y.tan(d/4);c=4/3*c*d;d*=4/3*e;e=[a,b];a=[a+c*k,b-d*f];b=[j+c*p,h-d*g];j=[j,h];a[0]=2*e[0]-a[0];a[1]=2*e[1]-a[1];if(i)return[a,
b,j].concat(n);else{n=[a,b,j].concat(n)[O]().split(",");i=[];j=0;for(h=n[q];j<h;j++)i[j]=j%2?w(n[j-1],n[j],m).y:w(n[j],n[j+1],m).x;return i}},Ba=function(a,b,c,e,f,d,g,j,h){var i=1-h;return{x:G(i,3)*a+G(i,2)*3*h*c+i*3*h*h*f+G(h,3)*g,y:G(i,3)*b+G(i,2)*3*h*e+i*3*h*h*d+G(h,3)*j}},Ab=J(function(a,b,c,e,f,d,g,j){var h=f-2*c+a-(g-2*f+c),i=2*(c-a)-2*(f-c),k=a-c,m=(-i+y.sqrt(i*i-4*h*k))/2/h;h=(-i-y.sqrt(i*i-4*h*k))/2/h;var n=[b,j],p=[a,g];M(m)>"1e12"&&(m=0.5);M(h)>"1e12"&&(h=0.5);if(m>0&&m<1){m=Ba(a,b,c,
e,f,d,g,j,m);p[F](m.x);n[F](m.y)}if(h>0&&h<1){m=Ba(a,b,c,e,f,d,g,j,h);p[F](m.x);n[F](m.y)}h=d-2*e+b-(j-2*d+e);i=2*(e-b)-2*(d-e);k=b-e;m=(-i+y.sqrt(i*i-4*h*k))/2/h;h=(-i-y.sqrt(i*i-4*h*k))/2/h;M(m)>"1e12"&&(m=0.5);M(h)>"1e12"&&(h=0.5);if(m>0&&m<1){m=Ba(a,b,c,e,f,d,g,j,m);p[F](m.x);n[F](m.y)}if(h>0&&h<1){m=Ba(a,b,c,e,f,d,g,j,h);p[F](m.x);n[F](m.y)}return{min:{x:ca[C](0,p),y:ca[C](0,n)},max:{x:W[C](0,p),y:W[C](0,n)}}}),za=J(function(a,b){var c=ra(a),e=b&&ra(b),f={x:0,y:0,bx:0,by:0,X:0,Y:0,qx:null,qy:null},
d={x:0,y:0,bx:0,by:0,X:0,Y:0,qx:null,qy:null},g=function(r,o){var s,H;if(!r)return["C",o.x,o.y,o.x,o.y,o.x,o.y];!(r[0]in{T:1,Q:1})&&(o.qx=o.qy=null);switch(r[0]){case "M":o.X=r[1];o.Y=r[2];break;case "A":r=["C"].concat(Wa[C](0,[o.x,o.y].concat(r.slice(1))));break;case "S":s=o.x+(o.x-(o.bx||o.x));H=o.y+(o.y-(o.by||o.y));r=["C",s,H].concat(r.slice(1));break;case "T":o.qx=o.x+(o.x-(o.qx||o.x));o.qy=o.y+(o.y-(o.qy||o.y));r=["C"].concat(Va(o.x,o.y,o.qx,o.qy,r[1],r[2]));break;case "Q":o.qx=r[1];o.qy=r[2];
r=["C"].concat(Va(o.x,o.y,r[1],r[2],r[3],r[4]));break;case "L":r=["C"].concat([o.x,o.y,r[1],r[2],r[1],r[2]]);break;case "H":r=["C"].concat([o.x,o.y,r[1],o.y,r[1],o.y]);break;case "V":r=["C"].concat([o.x,o.y,o.x,r[1],o.x,r[1]]);break;case "Z":r=["C"].concat([o.x,o.y,o.X,o.Y,o.X,o.Y])}return r},j=function(r,o){if(r[o][q]>7){r[o].shift();for(var s=r[o];s[q];)r.splice(o++,0,["C"].concat(s.splice(0,6)));r.splice(o,1);k=W(c[q],e&&e[q]||0)}},h=function(r,o,s,H,Q){if(r&&o&&r[Q][0]=="M"&&o[Q][0]!="M"){o.splice(Q,
0,["M",H.x,H.y]);s.bx=0;s.by=0;s.x=r[Q][1];s.y=r[Q][2];k=W(c[q],e&&e[q]||0)}},i=0,k=W(c[q],e&&e[q]||0);for(;i<k;i++){c[i]=g(c[i],f);j(c,i);e&&(e[i]=g(e[i],d));e&&j(e,i);h(c,e,f,d,i);h(e,c,d,f,i);var m=c[i],n=e&&e[i],p=m[q],w=e&&n[q];f.x=m[p-2];f.y=m[p-1];f.bx=x(m[p-4])||f.x;f.by=x(m[p-3])||f.y;d.bx=e&&(x(n[w-4])||d.x);d.by=e&&(x(n[w-3])||d.y);d.x=e&&n[w-2];d.y=e&&n[w-1]}return e?[c,e]:c},null,ya),Xa=J(function(a){for(var b=[],c=0,e=a[q];c<e;c++){var f={},d=a[c].match(/^([^:]*):?([\d\.]*)/);f.color=
l.getRGB(d[1]);if(f.color.error)return null;f.color=f.color.hex;d[2]&&(f.offset=d[2]+"%");b[F](f)}c=1;for(e=b[q]-1;c<e;c++)if(!b[c].offset){a=x(b[c-1].offset||0);d=0;for(f=c+1;f<e;f++)if(b[f].offset){d=b[f].offset;break}if(!d){d=100;f=e}d=x(d);for(d=(d-a)/(f-c+1);c<f;c++){a+=d;b[c].offset=a+"%"}}return b}),Ya=function(a,b,c,e){if(l.is(a,"string")||l.is(a,"object")){a=l.is(a,"string")?v.getElementById(a):a;if(a.tagName)return b==null?{container:a,width:a.style.pixelWidth||a.offsetWidth,height:a.style.pixelHeight||
a.offsetHeight}:{container:a,width:b,height:c}}else return{container:1,x:a,y:b,width:c,height:e}},Ka=function(a,b){var c=this,e;for(e in b)if(b[t](e)&&!(e in a))switch(typeof b[e]){case "function":(function(f){a[e]=a===c?f:function(){return f[C](c,arguments)}})(b[e]);break;case "object":a[e]=a[e]||{};Ka.call(this,a[e],b[e]);break;default:a[e]=b[e]}},qa=function(a,b){a==b.top&&(b.top=a.prev);a==b.bottom&&(b.bottom=a.next);a.next&&(a.next.prev=a.prev);a.prev&&(a.prev.next=a.next)},Za=function(a,b){if(b.top!==
a){qa(a,b);a.next=null;a.prev=b.top;b.top.next=a;b.top=a}},$a=function(a,b){if(b.bottom!==a){qa(a,b);a.next=b.bottom;a.prev=null;b.bottom.prev=a;b.bottom=a}},ab=function(a,b,c){qa(a,c);b==c.top&&(c.top=a);b.next&&(b.next.prev=a);a.next=b.next;a.prev=b;b.next=a},bb=function(a,b,c){qa(a,c);b==c.bottom&&(c.bottom=a);b.prev&&(b.prev.next=a);a.prev=b.prev;b.prev=a;a.next=b},cb=function(a){return function(){throw Error("Rapha\u00ebl: you are calling to method \u201c"+a+"\u201d of removed object");}};l.pathToRelative=
Ja;if(l.svg){E.svgns="http://www.w3.org/2000/svg";E.xlink="http://www.w3.org/1999/xlink";P=function(a){return+a+(~~a===a)*0.5};var u=function(a,b){if(b)for(var c in b)b[t](c)&&a.setAttribute(c,A(b[c]));else{a=v.createElementNS(E.svgns,a);a.style.webkitTapHighlightColor="rgba(0,0,0,0)";return a}};l[da]=function(){return"Your browser supports SVG.\nYou are running Rapha\u00ebl "+this.version};var db=function(a,b){var c=u("path");b.canvas&&b.canvas.appendChild(c);c=new D(c,b);c.type="path";ia(c,{fill:"none",
stroke:"#000",path:a});return c},sa=function(a,b,c){var e="linear",f=0.5,d=0.5,g=a.style;b=A(b).replace(Ta,function(k,m,n){e="radial";if(m&&n){f=x(m);d=x(n);k=(d>0.5)*2-1;G(f-0.5,2)+G(d-0.5,2)>0.25&&(d=y.sqrt(0.25-G(f-0.5,2))*k+0.5)&&d!=0.5&&(d=d.toFixed(5)-1.0E-5*k)}return""});b=b.split(/\s*\-\s*/);if(e=="linear"){var j=b.shift();j=-x(j);if(isNaN(j))return null;j=[0,0,y.cos(j*S/180),y.sin(j*S/180)];var h=1/(W(M(j[2]),M(j[3]))||1);j[2]*=h;j[3]*=h;if(j[2]<0){j[0]=-j[2];j[2]=0}if(j[3]<0){j[1]=-j[3];
j[3]=0}}b=Xa(b);if(!b)return null;h=a.getAttribute("fill");(h=h.match(/^url\(#(.*)\)$/))&&c.defs.removeChild(v.getElementById(h[1]));h=u(e+"Gradient");h.id=Z();u(h,e=="radial"?{fx:f,fy:d}:{x1:j[0],y1:j[1],x2:j[2],y2:j[3]});c.defs.appendChild(h);c=0;for(j=b[q];c<j;c++){var i=u("stop");u(i,{offset:b[c].offset?b[c].offset:!c?"0%":"100%","stop-color":b[c].color||"#fff"});h.appendChild(i)}u(a,{fill:"url(#"+h.id+")",opacity:1,"fill-opacity":1});g.fill="";g.opacity=1;return g.fillOpacity=1},La=function(a){var b=
a.getBBox();u(a.pattern,{patternTransform:l.format("translate({0},{1})",b.x,b.y)})},ia=function(a,b){var c={"":[0],none:[0],"-":[3,1],".":[1,1],"-.":[3,1,1,1],"-..":[3,1,1,1,1,1],". ":[1,3],"- ":[4,3],"--":[8,3],"- .":[4,3,1,3],"--.":[8,3,1,3],"--..":[8,3,1,3,1,3]},e=a.node,f=a.attrs,d=a.rotate(),g=function(w,r){if(r=c[ja.call(r)]){for(var o=w.attrs["stroke-width"]||"1",s={round:o,square:o,butt:0}[w.attrs["stroke-linecap"]||b["stroke-linecap"]]||0,H=[],Q=r[q];Q--;)H[Q]=r[Q]*o+(Q%2?1:-1)*s;u(e,{"stroke-dasharray":H[O](",")})}};
b[t]("rotation")&&(d=b.rotation);var j=A(d).split(R);if(j.length-1){j[1]=+j[1];j[2]=+j[2]}else j=null;x(d)&&a.rotate(0,true);for(var h in b)if(b[t](h))if(wa[t](h)){var i=b[h];f[h]=i;switch(h){case "blur":a.blur(i);break;case "rotation":a.rotate(i,true);break;case "href":case "title":case "target":var k=e.parentNode;if(ja.call(k.tagName)!="a"){var m=u("a");k.insertBefore(m,e);m.appendChild(e);k=m}h=="target"&&i=="blank"?k.setAttributeNS(a.paper.xlink,"show","new"):k.setAttributeNS(a.paper.xlink,h,
i);break;case "cursor":e.style.cursor=i;break;case "clip-rect":k=A(i).split(R);if(k[q]==4){a.clip&&a.clip.parentNode.parentNode.removeChild(a.clip.parentNode);var n=u("clipPath");m=u("rect");n.id=Z();u(m,{x:k[0],y:k[1],width:k[2],height:k[3]});n.appendChild(m);a.paper.defs.appendChild(n);u(e,{"clip-path":"url(#"+n.id+")"});a.clip=m}if(!i){(i=v.getElementById(e.getAttribute("clip-path").replace(/(^url\(#|\)$)/g,"")))&&i.parentNode.removeChild(i);u(e,{"clip-path":""});delete a.clip}break;case "path":if(a.type==
"path")u(e,{d:i?f.path=ra(i):"M0,0"});break;case "width":e.setAttribute(h,i);if(f.fx){h="x";i=f.x}else break;case "x":if(f.fx)i=-f.x-(f.width||0);case "rx":if(h=="rx"&&a.type=="rect")break;case "cx":j&&(h=="x"||h=="cx")&&(j[1]+=i-f[h]);e.setAttribute(h,i);a.pattern&&La(a);break;case "height":e.setAttribute(h,i);if(f.fy){h="y";i=f.y}else break;case "y":if(f.fy)i=-f.y-(f.height||0);case "ry":if(h=="ry"&&a.type=="rect")break;case "cy":j&&(h=="y"||h=="cy")&&(j[2]+=i-f[h]);e.setAttribute(h,i);a.pattern&&
La(a);break;case "r":a.type=="rect"?u(e,{rx:i,ry:i}):e.setAttribute(h,i);break;case "src":a.type=="image"&&e.setAttributeNS(a.paper.xlink,"href",i);break;case "stroke-width":e.style.strokeWidth=i;e.setAttribute(h,i);f["stroke-dasharray"]&&g(a,f["stroke-dasharray"]);break;case "stroke-dasharray":g(a,i);break;case "translation":i=A(i).split(R);i[0]=+i[0]||0;i[1]=+i[1]||0;if(j){j[1]+=i[0];j[2]+=i[1]}Ca.call(a,i[0],i[1]);break;case "scale":i=A(i).split(R);a.scale(+i[0]||1,+i[1]||+i[0]||1,isNaN(x(i[2]))?
null:+i[2],isNaN(x(i[3]))?null:+i[3]);break;case "fill":if(k=A(i).match(Sa)){n=u("pattern");var p=u("image");n.id=Z();u(n,{x:0,y:0,patternUnits:"userSpaceOnUse",height:1,width:1});u(p,{x:0,y:0});p.setAttributeNS(a.paper.xlink,"href",k[1]);n.appendChild(p);i=v.createElement("img");i.style.cssText="position:absolute;left:-9999em;top-9999em";i.onload=function(){u(n,{width:this.offsetWidth,height:this.offsetHeight});u(p,{width:this.offsetWidth,height:this.offsetHeight});v.body.removeChild(this);a.paper.safari()};
v.body.appendChild(i);i.src=k[1];a.paper.defs.appendChild(n);e.style.fill="url(#"+n.id+")";u(e,{fill:"url(#"+n.id+")"});a.pattern=n;a.pattern&&La(a);break}k=l.getRGB(i);if(k.error){if(({circle:1,ellipse:1}[t](a.type)||A(i).charAt()!="r")&&sa(e,i,a.paper)){f.gradient=i;f.fill="none";break}}else{delete b.gradient;delete f.gradient;!l.is(f.opacity,"undefined")&&l.is(b.opacity,"undefined")&&u(e,{opacity:f.opacity});!l.is(f["fill-opacity"],"undefined")&&l.is(b["fill-opacity"],"undefined")&&u(e,{"fill-opacity":f["fill-opacity"]})}k[t]("opacity")&&
u(e,{"fill-opacity":k.opacity>1?k.opacity/100:k.opacity});case "stroke":k=l.getRGB(i);e.setAttribute(h,k.hex);h=="stroke"&&k[t]("opacity")&&u(e,{"stroke-opacity":k.opacity>1?k.opacity/100:k.opacity});break;case "gradient":(({circle:1,ellipse:1})[t](a.type)||A(i).charAt()!="r")&&sa(e,i,a.paper);break;case "opacity":if(f.gradient&&!f[t]("stroke-opacity"))u(e,{"stroke-opacity":i>1?i/100:i});case "fill-opacity":if(f.gradient){if(k=v.getElementById(e.getAttribute("fill").replace(/^url\(#|\)$/g,""))){k=
k.getElementsByTagName("stop");k[k[q]-1].setAttribute("stop-opacity",i)}break}default:h=="font-size"&&(i=ga(i,10)+"px");k=h.replace(/(\-.)/g,function(w){return va.call(w.substring(1))});e.style[k]=i;e.setAttribute(h,i)}}Bb(a,b);if(j)a.rotate(j.join(L));else x(d)&&a.rotate(d,true)},Bb=function(a,b){if(!(a.type!="text"||!(b[t]("text")||b[t]("font")||b[t]("font-size")||b[t]("x")||b[t]("y")))){var c=a.attrs,e=a.node,f=e.firstChild?ga(v.defaultView.getComputedStyle(e.firstChild,"").getPropertyValue("font-size"),
10):10;if(b[t]("text")){for(c.text=b.text;e.firstChild;)e.removeChild(e.firstChild);for(var d=A(b.text).split("\n"),g=0,j=d[q];g<j;g++)if(d[g]){var h=u("tspan");g&&u(h,{dy:f*1.2,x:c.x});h.appendChild(v.createTextNode(d[g]));e.appendChild(h)}}else{d=e.getElementsByTagName("tspan");g=0;for(j=d[q];g<j;g++)g&&u(d[g],{dy:f*1.2,x:c.x})}u(e,{y:c.y});f=a.getBBox();(f=c.y-(f.y+f.height/2))&&l.is(f,"finite")&&u(e,{y:c.y+f})}},D=function(a,b){this[0]=a;this.id=l._oid++;this.node=a;a.raphael=this;this.paper=
b;this.attrs=this.attrs||{};this.transformations=[];this._={tx:0,ty:0,rt:{deg:0,cx:0,cy:0},sx:1,sy:1};!b.bottom&&(b.bottom=this);(this.prev=b.top)&&(b.top.next=this);b.top=this;this.next=null},B=D[z];D[z].rotate=function(a,b,c){if(this.removed)return this;if(a==null){if(this._.rt.cx)return[this._.rt.deg,this._.rt.cx,this._.rt.cy][O](L);return this._.rt.deg}var e=this.getBBox();a=A(a).split(R);if(a[q]-1){b=x(a[1]);c=x(a[2])}a=x(a[0]);if(b!=null&&b!==false)this._.rt.deg=a;else this._.rt.deg+=a;c==null&&
(b=null);this._.rt.cx=b;this._.rt.cy=c;b=b==null?e.x+e.width/2:b;c=c==null?e.y+e.height/2:c;if(this._.rt.deg){this.transformations[0]=l.format("rotate({0} {1} {2})",this._.rt.deg,b,c);this.clip&&u(this.clip,{transform:l.format("rotate({0} {1} {2})",-this._.rt.deg,b,c)})}else{this.transformations[0]="";this.clip&&u(this.clip,{transform:""})}u(this.node,{transform:this.transformations[O](L)});return this};D[z].hide=function(){!this.removed&&(this.node.style.display="none");return this};D[z].show=function(){!this.removed&&
(this.node.style.display="");return this};D[z].remove=function(){if(!this.removed){qa(this,this.paper);this.node.parentNode.removeChild(this.node);for(var a in this)delete this[a];this.removed=true}};D[z].getBBox=function(){if(this.removed)return this;if(this.type=="path")return Aa(this.attrs.path);if(this.node.style.display=="none"){this.show();var a=true}var b={};try{b=this.node.getBBox()}catch(c){}finally{b=b||{}}if(this.type=="text"){b={x:b.x,y:Infinity,width:0,height:0};for(var e=0,f=this.node.getNumberOfChars();e<
f;e++){var d=this.node.getExtentOfChar(e);d.y<b.y&&(b.y=d.y);d.y+d.height-b.y>b.height&&(b.height=d.y+d.height-b.y);d.x+d.width-b.x>b.width&&(b.width=d.x+d.width-b.x)}}a&&this.hide();return b};D[z].attr=function(a,b){if(this.removed)return this;if(a==null){var c={},e;for(e in this.attrs)if(this.attrs[t](e))c[e]=this.attrs[e];this._.rt.deg&&(c.rotation=this.rotate());(this._.sx!=1||this._.sy!=1)&&(c.scale=this.scale());c.gradient&&c.fill=="none"&&(c.fill=c.gradient)&&delete c.gradient;return c}if(b==
null&&l.is(a,"string")){if(a=="translation")return Ca.call(this);if(a=="rotation")return this.rotate();if(a=="scale")return this.scale();if(a=="fill"&&this.attrs.fill=="none"&&this.attrs.gradient)return this.attrs.gradient;return this.attrs[a]}if(b==null&&l.is(a,X)){e={};c=0;for(var f=a.length;c<f;c++)e[a[c]]=this.attr(a[c]);return e}if(b!=null){c={};c[a]=b}else if(a!=null&&l.is(a,"object"))c=a;for(f in this.paper.customAttributes)if(this.paper.customAttributes[t](f)&&c[t](f)&&l.is(this.paper.customAttributes[f],
"function")){e=this.paper.customAttributes[f].apply(this,[].concat(c[f]));this.attrs[f]=c[f];for(var d in e)if(e[t](d))c[d]=e[d]}ia(this,c);return this};D[z].toFront=function(){if(this.removed)return this;this.node.parentNode.appendChild(this.node);var a=this.paper;a.top!=this&&Za(this,a);return this};D[z].toBack=function(){if(this.removed)return this;if(this.node.parentNode.firstChild!=this.node){this.node.parentNode.insertBefore(this.node,this.node.parentNode.firstChild);$a(this,this.paper)}return this};
D[z].insertAfter=function(a){if(this.removed)return this;var b=a.node||a[a.length-1].node;b.nextSibling?b.parentNode.insertBefore(this.node,b.nextSibling):b.parentNode.appendChild(this.node);ab(this,a,this.paper);return this};D[z].insertBefore=function(a){if(this.removed)return this;var b=a.node||a[0].node;b.parentNode.insertBefore(this.node,b);bb(this,a,this.paper);return this};D[z].blur=function(a){if(+a!==0){var b=u("filter"),c=u("feGaussianBlur");this.attrs.blur=a;b.id=Z();u(c,{stdDeviation:+a||
1.5});b.appendChild(c);this.paper.defs.appendChild(b);this._blur=b;u(this.node,{filter:"url(#"+b.id+")"})}else{if(this._blur){this._blur.parentNode.removeChild(this._blur);delete this._blur;delete this.attrs.blur}this.node.removeAttribute("filter")}};var eb=function(a,b,c,e){var f=u("circle");a.canvas&&a.canvas.appendChild(f);a=new D(f,a);a.attrs={cx:b,cy:c,r:e,fill:"none",stroke:"#000"};a.type="circle";u(f,a.attrs);return a},fb=function(a,b,c,e,f,d){var g=u("rect");a.canvas&&a.canvas.appendChild(g);
a=new D(g,a);a.attrs={x:b,y:c,width:e,height:f,r:d||0,rx:d||0,ry:d||0,fill:"none",stroke:"#000"};a.type="rect";u(g,a.attrs);return a},gb=function(a,b,c,e,f){var d=u("ellipse");a.canvas&&a.canvas.appendChild(d);a=new D(d,a);a.attrs={cx:b,cy:c,rx:e,ry:f,fill:"none",stroke:"#000"};a.type="ellipse";u(d,a.attrs);return a},hb=function(a,b,c,e,f,d){var g=u("image");u(g,{x:c,y:e,width:f,height:d,preserveAspectRatio:"none"});g.setAttributeNS(a.xlink,"href",b);a.canvas&&a.canvas.appendChild(g);a=new D(g,a);
a.attrs={x:c,y:e,width:f,height:d,src:b};a.type="image";return a},ib=function(a,b,c,e){var f=u("text");u(f,{x:b,y:c,"text-anchor":"middle"});a.canvas&&a.canvas.appendChild(f);a=new D(f,a);a.attrs={x:b,y:c,"text-anchor":"middle",text:e,font:wa.font,stroke:"none",fill:"#000"};a.type="text";ia(a,a.attrs);return a},jb=function(a,b){this.width=a||this.width;this.height=b||this.height;this.canvas.setAttribute("width",this.width);this.canvas.setAttribute("height",this.height);return this},Fa=function(){var a=
Ya[C](0,arguments),b=a&&a.container,c=a.x,e=a.y,f=a.width;a=a.height;if(!b)throw Error("SVG container not found.");var d=u("svg");c=c||0;e=e||0;f=f||512;a=a||342;u(d,{xmlns:"http://www.w3.org/2000/svg",version:1.1,width:f,height:a});if(b==1){d.style.cssText="position:absolute;left:"+c+"px;top:"+e+"px";v.body.appendChild(d)}else b.firstChild?b.insertBefore(d,b.firstChild):b.appendChild(d);b=new la;b.width=f;b.height=a;b.canvas=d;Ka.call(b,b,l.fn);b.clear();return b};E.clear=function(){for(var a=this.canvas;a.firstChild;)a.removeChild(a.firstChild);
this.bottom=this.top=null;(this.desc=u("desc")).appendChild(v.createTextNode("Created with Rapha\u00ebl"));a.appendChild(this.desc);a.appendChild(this.defs=u("defs"))};E.remove=function(){this.canvas.parentNode&&this.canvas.parentNode.removeChild(this.canvas);for(var a in this)this[a]=cb(a)}}if(l.vml){var kb={M:"m",L:"l",C:"c",Z:"x",m:"t",l:"r",c:"v",z:"x"},Cb=/([clmz]),?([^clmz]*)/gi,Db=/ progid:\S+Blur\([^\)]+\)/g,Eb=/-?[^,\s-]+/g,ta=1E3+L+1E3,ua={path:1,rect:1},Fb=function(a){var b=/[ahqstv]/ig,c=ra;
A(a).match(b)&&(c=za);b=/[clmz]/g;if(c==ra&&!A(a).match(b))return a=A(a).replace(Cb,function(h,i,k){var m=[],n=ja.call(i)=="m",p=kb[i];k.replace(Eb,function(w){if(n&&m[q]==2){p+=m+kb[i=="m"?"l":"L"];m=[]}m[F](P(w*10))});return p+m});b=c(a);var e;a=[];for(var f=0,d=b[q];f<d;f++){c=b[f];e=ja.call(b[f][0]);e=="z"&&(e="x");for(var g=1,j=c[q];g<j;g++)e+=P(c[g]*10)+(g!=j-1?",":"");a[F](e)}return a[O](L)};l[da]=function(){return"Your browser doesn\u2019t support SVG. Falling down to VML.\nYou are running Rapha\u00ebl "+
this.version};db=function(a,b){var c=U("group");c.style.cssText="position:absolute;left:0;top:0;width:"+b.width+"px;height:"+b.height+"px";c.coordsize=b.coordsize;c.coordorigin=b.coordorigin;var e=U("shape"),f=e.style;f.width=b.width+"px";f.height=b.height+"px";e.coordsize=ta;e.coordorigin=b.coordorigin;c.appendChild(e);e=new D(e,c,b);f={fill:"none",stroke:"#000"};a&&(f.path=a);e.type="path";e.path=[];e.Path="";ia(e,f);b.canvas.appendChild(c);return e};ia=function(a,b){a.attrs=a.attrs||{};var c=a.node,
e=a.attrs,f=c.style,d;d=(b.x!=e.x||b.y!=e.y||b.width!=e.width||b.height!=e.height||b.r!=e.r)&&a.type=="rect";for(var g in b)if(b[t](g))e[g]=b[g];if(d){e.path=lb(e.x,e.y,e.width,e.height,e.r);a.X=e.x;a.Y=e.y;a.W=e.width;a.H=e.height}b.href&&(c.href=b.href);b.title&&(c.title=b.title);b.target&&(c.target=b.target);b.cursor&&(f.cursor=b.cursor);"blur"in b&&a.blur(b.blur);if(b.path&&a.type=="path"||d)c.path=Fb(e.path);b.rotation!=null&&a.rotate(b.rotation,true);if(b.translation){d=A(b.translation).split(R);
Ca.call(a,d[0],d[1]);if(a._.rt.cx!=null){a._.rt.cx+=+d[0];a._.rt.cy+=+d[1];a.setBox(a.attrs,d[0],d[1])}}if(b.scale){d=A(b.scale).split(R);a.scale(+d[0]||1,+d[1]||+d[0]||1,+d[2]||null,+d[3]||null)}if("clip-rect"in b){d=A(b["clip-rect"]).split(R);if(d[q]==4){d[2]=+d[2]+ +d[0];d[3]=+d[3]+ +d[1];g=c.clipRect||v.createElement("div");var j=g.style,h=c.parentNode;j.clip=l.format("rect({1}px {2}px {3}px {0}px)",d);if(!c.clipRect){j.position="absolute";j.top=0;j.left=0;j.width=a.paper.width+"px";j.height=
a.paper.height+"px";h.parentNode.insertBefore(g,h);g.appendChild(h);c.clipRect=g}}if(!b["clip-rect"])c.clipRect&&(c.clipRect.style.clip="")}if(a.type=="image"&&b.src)c.src=b.src;if(a.type=="image"&&b.opacity){c.filterOpacity=" progid:DXImageTransform.Microsoft.Alpha(opacity="+b.opacity*100+")";f.filter=(c.filterMatrix||"")+(c.filterOpacity||"")}b.font&&(f.font=b.font);b["font-family"]&&(f.fontFamily='"'+b["font-family"].split(",")[0].replace(/^['"]+|['"]+$/g,"")+'"');b["font-size"]&&(f.fontSize=b["font-size"]);
b["font-weight"]&&(f.fontWeight=b["font-weight"]);b["font-style"]&&(f.fontStyle=b["font-style"]);if(b.opacity!=null||b["stroke-width"]!=null||b.fill!=null||b.stroke!=null||b["stroke-width"]!=null||b["stroke-opacity"]!=null||b["fill-opacity"]!=null||b["stroke-dasharray"]!=null||b["stroke-miterlimit"]!=null||b["stroke-linejoin"]!=null||b["stroke-linecap"]!=null){c=a.shape||c;d=c.getElementsByTagName("fill")&&c.getElementsByTagName("fill")[0];g=false;!d&&(g=d=U("fill"));if("fill-opacity"in b||"opacity"in
b){f=((+e["fill-opacity"]+1||2)-1)*((+e.opacity+1||2)-1)*((+l.getRGB(b.fill).o+1||2)-1);f=ca(W(f,0),1);d.opacity=f}b.fill&&(d.on=true);if(d.on==null||b.fill=="none")d.on=false;if(d.on&&b.fill)if(f=b.fill.match(Sa)){d.src=f[1];d.type="tile"}else{d.color=l.getRGB(b.fill).hex;d.src="";d.type="solid";if(l.getRGB(b.fill).error&&(a.type in{circle:1,ellipse:1}||A(b.fill).charAt()!="r")&&sa(a,b.fill)){e.fill="none";e.gradient=b.fill}}g&&c.appendChild(d);d=c.getElementsByTagName("stroke")&&c.getElementsByTagName("stroke")[0];
g=false;!d&&(g=d=U("stroke"));if(b.stroke&&b.stroke!="none"||b["stroke-width"]||b["stroke-opacity"]!=null||b["stroke-dasharray"]||b["stroke-miterlimit"]||b["stroke-linejoin"]||b["stroke-linecap"])d.on=true;(b.stroke=="none"||d.on==null||b.stroke==0||b["stroke-width"]==0)&&(d.on=false);f=l.getRGB(b.stroke);d.on&&b.stroke&&(d.color=f.hex);f=((+e["stroke-opacity"]+1||2)-1)*((+e.opacity+1||2)-1)*((+f.o+1||2)-1);j=(x(b["stroke-width"])||1)*0.75;f=ca(W(f,0),1);b["stroke-width"]==null&&(j=e["stroke-width"]);
b["stroke-width"]&&(d.weight=j);j&&j<1&&(f*=j)&&(d.weight=1);d.opacity=f;b["stroke-linejoin"]&&(d.joinstyle=b["stroke-linejoin"]||"miter");d.miterlimit=b["stroke-miterlimit"]||8;b["stroke-linecap"]&&(d.endcap=b["stroke-linecap"]=="butt"?"flat":b["stroke-linecap"]=="square"?"square":"round");if(b["stroke-dasharray"]){f={"-":"shortdash",".":"shortdot","-.":"shortdashdot","-..":"shortdashdotdot",". ":"dot","- ":"dash","--":"longdash","- .":"dashdot","--.":"longdashdot","--..":"longdashdotdot"};d.dashstyle=
f[t](b["stroke-dasharray"])?f[b["stroke-dasharray"]]:""}g&&c.appendChild(d)}if(a.type=="text"){f=a.paper.span.style;e.font&&(f.font=e.font);e["font-family"]&&(f.fontFamily=e["font-family"]);e["font-size"]&&(f.fontSize=e["font-size"]);e["font-weight"]&&(f.fontWeight=e["font-weight"]);e["font-style"]&&(f.fontStyle=e["font-style"]);a.node.string&&(a.paper.span.innerHTML=A(a.node.string).replace(/</g,"&#60;").replace(/&/g,"&#38;").replace(/\n/g,"<br>"));a.W=e.w=a.paper.span.offsetWidth;a.H=e.h=a.paper.span.offsetHeight;
a.X=e.x;a.Y=e.y+P(a.H/2);switch(e["text-anchor"]){case "start":a.node.style["v-text-align"]="left";a.bbx=P(a.W/2);break;case "end":a.node.style["v-text-align"]="right";a.bbx=-P(a.W/2);break;default:a.node.style["v-text-align"]="center"}}};sa=function(a,b){a.attrs=a.attrs||{};var c,e="linear",f=".5 .5";a.attrs.gradient=b;b=A(b).replace(Ta,function(k,m,n){e="radial";if(m&&n){m=x(m);n=x(n);G(m-0.5,2)+G(n-0.5,2)>0.25&&(n=y.sqrt(0.25-G(m-0.5,2))*((n>0.5)*2-1)+0.5);f=m+L+n}return""});b=b.split(/\s*\-\s*/);
if(e=="linear"){var d=b.shift();d=-x(d);if(isNaN(d))return null}var g=Xa(b);if(!g)return null;a=a.shape||a.node;c=a.getElementsByTagName("fill")[0]||U("fill");!c.parentNode&&a.appendChild(c);if(g[q]){c.on=true;c.method="none";c.color=g[0].color;c.color2=g[g[q]-1].color;for(var j=[],h=0,i=g[q];h<i;h++)g[h].offset&&j[F](g[h].offset+L+g[h].color);c.colors&&(c.colors.value=j[q]?j[O]():"0% "+c.color);if(e=="radial"){c.type="gradientradial";c.focus="100%";c.focussize=f;c.focusposition=f}else{c.type="gradient";
c.angle=(270-d)%360}}return 1};D=function(a,b,c){this[0]=a;this.id=l._oid++;this.node=a;a.raphael=this;this.Y=this.X=0;this.attrs={};this.Group=b;this.paper=c;this._={tx:0,ty:0,rt:{deg:0},sx:1,sy:1};!c.bottom&&(c.bottom=this);(this.prev=c.top)&&(c.top.next=this);c.top=this;this.next=null};B=D[z];B.rotate=function(a,b,c){if(this.removed)return this;if(a==null){if(this._.rt.cx)return[this._.rt.deg,this._.rt.cx,this._.rt.cy][O](L);return this._.rt.deg}a=A(a).split(R);if(a[q]-1){b=x(a[1]);c=x(a[2])}a=
x(a[0]);if(b!=null)this._.rt.deg=a;else this._.rt.deg+=a;c==null&&(b=null);this._.rt.cx=b;this._.rt.cy=c;this.setBox(this.attrs,b,c);this.Group.style.rotation=this._.rt.deg;return this};B.setBox=function(a,b,c){if(this.removed)return this;var e=this.Group.style,f=this.shape&&this.shape.style||this.node.style;a=a||{};for(var d in a)if(a[t](d))this.attrs[d]=a[d];b=b||this._.rt.cx;c=c||this._.rt.cy;var g=this.attrs,j;switch(this.type){case "circle":a=g.cx-g.r;d=g.cy-g.r;j=g=g.r*2;break;case "ellipse":a=
g.cx-g.rx;d=g.cy-g.ry;j=g.rx*2;g=g.ry*2;break;case "image":a=+g.x;d=+g.y;j=g.width||0;g=g.height||0;break;case "text":this.textpath.v=["m",P(g.x),", ",P(g.y-2),"l",P(g.x)+1,", ",P(g.y-2)][O]("");a=g.x-P(this.W/2);d=g.y-this.H/2;j=this.W;g=this.H;break;case "rect":case "path":if(this.attrs.path){g=Aa(this.attrs.path);a=g.x;d=g.y;j=g.width;g=g.height}else{d=a=0;j=this.paper.width;g=this.paper.height}break;default:d=a=0;j=this.paper.width;g=this.paper.height}b=(b==null?a+j/2:b)-this.paper.width/2;c=
(c==null?d+g/2:c)-this.paper.height/2;var h;e.left!=(h=b+"px")&&(e.left=h);e.top!=(h=c+"px")&&(e.top=h);this.X=ua[t](this.type)?-b:a;this.Y=ua[t](this.type)?-c:d;this.W=j;this.H=g;if(ua[t](this.type)){f.left!=(h=-b*10+"px")&&(f.left=h);f.top!=(h=-c*10+"px")&&(f.top=h)}else if(this.type=="text"){f.left!=(h=-b+"px")&&(f.left=h);f.top!=(h=-c+"px")&&(f.top=h)}else{e.width!=(h=this.paper.width+"px")&&(e.width=h);e.height!=(h=this.paper.height+"px")&&(e.height=h);f.left!=(h=a-b+"px")&&(f.left=h);f.top!=
(h=d-c+"px")&&(f.top=h);f.width!=(h=j+"px")&&(f.width=h);f.height!=(h=g+"px")&&(f.height=h)}};B.hide=function(){!this.removed&&(this.Group.style.display="none");return this};B.show=function(){!this.removed&&(this.Group.style.display="block");return this};B.getBBox=function(){if(this.removed)return this;if(ua[t](this.type))return Aa(this.attrs.path);return{x:this.X+(this.bbx||0),y:this.Y,width:this.W,height:this.H}};B.remove=function(){if(!this.removed){qa(this,this.paper);this.node.parentNode.removeChild(this.node);
this.Group.parentNode.removeChild(this.Group);this.shape&&this.shape.parentNode.removeChild(this.shape);for(var a in this)delete this[a];this.removed=true}};B.attr=function(a,b){if(this.removed)return this;if(a==null){var c={},e;for(e in this.attrs)if(this.attrs[t](e))c[e]=this.attrs[e];this._.rt.deg&&(c.rotation=this.rotate());(this._.sx!=1||this._.sy!=1)&&(c.scale=this.scale());c.gradient&&c.fill=="none"&&(c.fill=c.gradient)&&delete c.gradient;return c}if(b==null&&l.is(a,"string")){if(a=="translation")return Ca.call(this);
if(a=="rotation")return this.rotate();if(a=="scale")return this.scale();if(a=="fill"&&this.attrs.fill=="none"&&this.attrs.gradient)return this.attrs.gradient;return this.attrs[a]}if(this.attrs&&b==null&&l.is(a,X)){var f={};e=0;for(c=a[q];e<c;e++)f[a[e]]=this.attr(a[e]);return f}if(b!=null){c={};c[a]=b}b==null&&l.is(a,"object")&&(c=a);if(c){for(f in this.paper.customAttributes)if(this.paper.customAttributes[t](f)&&c[t](f)&&l.is(this.paper.customAttributes[f],"function")){e=this.paper.customAttributes[f].apply(this,
[].concat(c[f]));this.attrs[f]=c[f];for(var d in e)if(e[t](d))c[d]=e[d]}if(c.text&&this.type=="text")this.node.string=c.text;ia(this,c);if(c.gradient&&({circle:1,ellipse:1}[t](this.type)||A(c.gradient).charAt()!="r"))sa(this,c.gradient);(!ua[t](this.type)||this._.rt.deg)&&this.setBox(this.attrs)}return this};B.toFront=function(){!this.removed&&this.Group.parentNode.appendChild(this.Group);this.paper.top!=this&&Za(this,this.paper);return this};B.toBack=function(){if(this.removed)return this;if(this.Group.parentNode.firstChild!=
this.Group){this.Group.parentNode.insertBefore(this.Group,this.Group.parentNode.firstChild);$a(this,this.paper)}return this};B.insertAfter=function(a){if(this.removed)return this;if(a.constructor==Y)a=a[a.length-1];a.Group.nextSibling?a.Group.parentNode.insertBefore(this.Group,a.Group.nextSibling):a.Group.parentNode.appendChild(this.Group);ab(this,a,this.paper);return this};B.insertBefore=function(a){if(this.removed)return this;if(a.constructor==Y)a=a[0];a.Group.parentNode.insertBefore(this.Group,
a.Group);bb(this,a,this.paper);return this};B.blur=function(a){var b=this.node.runtimeStyle,c=b.filter;c=c.replace(Db,"");if(+a!==0){this.attrs.blur=a;b.filter=c+L+" progid:DXImageTransform.Microsoft.Blur(pixelradius="+(+a||1.5)+")";b.margin=l.format("-{0}px 0 0 -{0}px",P(+a||1.5))}else{b.filter=c;b.margin=0;delete this.attrs.blur}};eb=function(a,b,c,e){var f=U("group"),d=U("oval");f.style.cssText="position:absolute;left:0;top:0;width:"+a.width+"px;height:"+a.height+"px";f.coordsize=ta;f.coordorigin=
a.coordorigin;f.appendChild(d);d=new D(d,f,a);d.type="circle";ia(d,{stroke:"#000",fill:"none"});d.attrs.cx=b;d.attrs.cy=c;d.attrs.r=e;d.setBox({x:b-e,y:c-e,width:e*2,height:e*2});a.canvas.appendChild(f);return d};var lb=function(a,b,c,e,f){return f?l.format("M{0},{1}l{2},0a{3},{3},0,0,1,{3},{3}l0,{5}a{3},{3},0,0,1,{4},{3}l{6},0a{3},{3},0,0,1,{4},{4}l0,{7}a{3},{3},0,0,1,{3},{4}z",a+f,b,c-f*2,f,-f,e-f*2,f*2-c,f*2-e):l.format("M{0},{1}l{2},0,0,{3},{4},0z",a,b,c,e,-c)};fb=function(a,b,c,e,f,d){var g=
lb(b,c,e,f,d);a=a.path(g);var j=a.attrs;a.X=j.x=b;a.Y=j.y=c;a.W=j.width=e;a.H=j.height=f;j.r=d;j.path=g;a.type="rect";return a};gb=function(a,b,c,e,f){var d=U("group"),g=U("oval");d.style.cssText="position:absolute;left:0;top:0;width:"+a.width+"px;height:"+a.height+"px";d.coordsize=ta;d.coordorigin=a.coordorigin;d.appendChild(g);g=new D(g,d,a);g.type="ellipse";ia(g,{stroke:"#000"});g.attrs.cx=b;g.attrs.cy=c;g.attrs.rx=e;g.attrs.ry=f;g.setBox({x:b-e,y:c-f,width:e*2,height:f*2});a.canvas.appendChild(d);
return g};hb=function(a,b,c,e,f,d){var g=U("group"),j=U("image");g.style.cssText="position:absolute;left:0;top:0;width:"+a.width+"px;height:"+a.height+"px";g.coordsize=ta;g.coordorigin=a.coordorigin;j.src=b;g.appendChild(j);j=new D(j,g,a);j.type="image";j.attrs.src=b;j.attrs.x=c;j.attrs.y=e;j.attrs.w=f;j.attrs.h=d;j.setBox({x:c,y:e,width:f,height:d});a.canvas.appendChild(g);return j};ib=function(a,b,c,e){var f=U("group"),d=U("shape"),g=d.style,j=U("path"),h=U("textpath");f.style.cssText="position:absolute;left:0;top:0;width:"+
a.width+"px;height:"+a.height+"px";f.coordsize=ta;f.coordorigin=a.coordorigin;j.v=l.format("m{0},{1}l{2},{1}",P(b*10),P(c*10),P(b*10)+1);j.textpathok=true;g.width=a.width;g.height=a.height;h.string=A(e);h.on=true;d.appendChild(h);d.appendChild(j);f.appendChild(d);g=new D(h,f,a);g.shape=d;g.textpath=j;g.type="text";g.attrs.text=e;g.attrs.x=b;g.attrs.y=c;g.attrs.w=1;g.attrs.h=1;ia(g,{font:wa.font,stroke:"none",fill:"#000"});g.setBox();a.canvas.appendChild(f);return g};jb=function(a,b){var c=this.canvas.style;
a==+a&&(a+="px");b==+b&&(b+="px");c.width=a;c.height=b;c.clip="rect(0 "+a+" "+b+" 0)";return this};var U;v.createStyleSheet().addRule(".rvml","behavior:url(#default#VML)");try{!v.namespaces.rvml&&v.namespaces.add("rvml","urn:schemas-microsoft-com:vml");U=function(a){return v.createElement("<rvml:"+a+' class="rvml">')}}catch(Mb){U=function(a){return v.createElement("<"+a+' xmlns="urn:schemas-microsoft.com:vml" class="rvml">')}}Fa=function(){var a=Ya[C](0,arguments),b=a.container,c=a.height,e=a.width,
f=a.x;a=a.y;if(!b)throw Error("VML container not found.");var d=new la,g=d.canvas=v.createElement("div"),j=g.style;f=f||0;a=a||0;e=e||512;c=c||342;e==+e&&(e+="px");c==+c&&(c+="px");d.width=1E3;d.height=1E3;d.coordsize=1E4+L+1E4;d.coordorigin="0 0";d.span=v.createElement("span");d.span.style.cssText="position:absolute;left:-9999em;top:-9999em;padding:0;margin:0;line-height:1;display:inline;";g.appendChild(d.span);j.cssText=l.format("top:0;left:0;width:{0};height:{1};display:inline-block;position:relative;clip:rect(0 {0} {1} 0);overflow:hidden",
e,c);if(b==1){v.body.appendChild(g);j.left=f+"px";j.top=a+"px";j.position="absolute"}else b.firstChild?b.insertBefore(g,b.firstChild):b.appendChild(g);Ka.call(d,d,l.fn);return d};E.clear=function(){this.canvas.innerHTML="";this.span=v.createElement("span");this.span.style.cssText="position:absolute;left:-9999em;top:-9999em;padding:0;margin:0;line-height:1;display:inline;";this.canvas.appendChild(this.span);this.bottom=this.top=null};E.remove=function(){this.canvas.parentNode.removeChild(this.canvas);
for(var a in this)this[a]=cb(a);return true}}$=navigator.userAgent.match(/Version\/(.*?)\s/);E.safari=navigator.vendor=="Apple Computer, Inc."&&($&&$[1]<4||navigator.platform.slice(0,2)=="iP")?function(){var a=this.rect(-99,-99,this.width+99,this.height+99).attr({stroke:"none"});K.setTimeout(function(){a.remove()})}:function(){};var Gb=function(){this.returnValue=false},Hb=function(){return this.originalEvent.preventDefault()},Ib=function(){this.cancelBubble=true},Jb=function(){return this.originalEvent.stopPropagation()},
Kb=function(){if(v.addEventListener)return function(a,b,c,e){var f=oa&&Ga[b]?Ga[b]:b,d=function(g){if(oa&&Ga[t](b))for(var j=0,h=g.targetTouches&&g.targetTouches.length;j<h;j++)if(g.targetTouches[j].target==a){h=g;g=g.targetTouches[j];g.originalEvent=h;g.preventDefault=Hb;g.stopPropagation=Jb;break}return c.call(e,g)};a.addEventListener(f,d,false);return function(){a.removeEventListener(f,d,false);return true}};else if(v.attachEvent)return function(a,b,c,e){var f=function(d){d=d||K.event;d.preventDefault=
d.preventDefault||Gb;d.stopPropagation=d.stopPropagation||Ib;return c.call(e,d)};a.attachEvent("on"+b,f);return function(){a.detachEvent("on"+b,f);return true}}}(),aa=[],Ma=function(a){for(var b=a.clientX,c=a.clientY,e=v.documentElement.scrollTop||v.body.scrollTop,f=v.documentElement.scrollLeft||v.body.scrollLeft,d,g=aa.length;g--;){d=aa[g];if(oa)for(var j=a.touches.length,h;j--;){h=a.touches[j];if(h.identifier==d.el._drag.id){b=h.clientX;c=h.clientY;(a.originalEvent?a.originalEvent:a).preventDefault();
break}}else a.preventDefault();b+=f;c+=e;d.move&&d.move.call(d.move_scope||d.el,b-d.el._drag.x,c-d.el._drag.y,b,c,a)}},Na=function(a){l.unmousemove(Ma).unmouseup(Na);for(var b=aa.length,c;b--;){c=aa[b];c.el._drag={};c.end&&c.end.call(c.end_scope||c.start_scope||c.move_scope||c.el,a)}aa=[]};for($=pa[q];$--;)(function(a){l[a]=D[z][a]=function(b,c){if(l.is(b,"function")){this.events=this.events||[];this.events.push({name:a,f:b,unbind:Kb(this.shape||this.node||v,a,b,c||this)})}return this};l["un"+a]=
D[z]["un"+a]=function(b){for(var c=this.events,e=c[q];e--;)if(c[e].name==a&&c[e].f==b){c[e].unbind();c.splice(e,1);!c.length&&delete this.events;break}return this}})(pa[$]);B.hover=function(a,b,c,e){return this.mouseover(a,c).mouseout(b,e||c)};B.unhover=function(a,b){return this.unmouseover(a).unmouseout(b)};B.drag=function(a,b,c,e,f,d){this._drag={};this.mousedown(function(g){(g.originalEvent||g).preventDefault();var j=v.documentElement.scrollTop||v.body.scrollTop,h=v.documentElement.scrollLeft||
v.body.scrollLeft;this._drag.x=g.clientX+h;this._drag.y=g.clientY+j;this._drag.id=g.identifier;b&&b.call(f||e||this,g.clientX+h,g.clientY+j,g);!aa.length&&l.mousemove(Ma).mouseup(Na);aa.push({el:this,move:a,end:c,move_scope:e,start_scope:f,end_scope:d})});return this};B.undrag=function(a,b,c){for(b=aa.length;b--;)aa[b].el==this&&aa[b].move==a&&aa[b].end==c&&aa.splice(b++,1);!aa.length&&l.unmousemove(Ma).unmouseup(Na)};E.circle=function(a,b,c){return eb(this,a||0,b||0,c||0)};E.rect=function(a,b,c,
e,f){return fb(this,a||0,b||0,c||0,e||0,f||0)};E.ellipse=function(a,b,c,e){return gb(this,a||0,b||0,c||0,e||0)};E.path=function(a){a&&!l.is(a,"string")&&!l.is(a[0],X)&&(a+="");return db(l.format[C](l,arguments),this)};E.image=function(a,b,c,e,f){return hb(this,a||"about:blank",b||0,c||0,e||0,f||0)};E.text=function(a,b,c){return ib(this,a||0,b||0,A(c))};E.set=function(a){arguments[q]>1&&(a=Array[z].splice.call(arguments,0,arguments[q]));return new Y(a)};E.setSize=jb;E.top=E.bottom=null;E.raphael=l;
B.resetScale=function(){if(this.removed)return this;this._.sx=1;this._.sy=1;this.attrs.scale="1 1"};B.scale=function(a,b,c,e){if(this.removed)return this;if(a==null&&b==null)return{x:this._.sx,y:this._.sy,toString:V};b=b||a;!+b&&(b=a);var f,d,g=this.attrs;if(a!=0){var j=this.getBBox(),h=j.x+j.width/2,i=j.y+j.height/2;f=M(a/this._.sx);d=M(b/this._.sy);c=+c||c==0?c:h;e=+e||e==0?e:i;var k=this._.sx>0,m=this._.sy>0;j=~~(a/M(a));var n=~~(b/M(b)),p=f*j,w=d*n,r=this.node.style;h=c+M(h-c)*p*(h>c==k?1:-1);
i=e+M(i-e)*w*(i>e==m?1:-1);var o=a*j>b*n?d:f;switch(this.type){case "rect":case "image":var s=g.width*f,H=g.height*d;this.attr({height:H,r:g.r*o,width:s,x:h-s/2,y:i-H/2});break;case "circle":case "ellipse":this.attr({rx:g.rx*f,ry:g.ry*d,r:g.r*o,cx:h,cy:i});break;case "text":this.attr({x:h,y:i});break;case "path":o=Ja(g.path);var Q=true;k=k?p:f;m=m?w:d;w=0;for(p=o[q];w<p;w++){var T=o[w],I=va.call(T[0]);if(!(I=="M"&&Q)){Q=false;if(I=="A"){T[o[w][q]-2]*=k;T[o[w][q]-1]*=m;T[1]*=f;T[2]*=d;T[5]=+(j+n?!!+T[5]:
!+T[5])}else if(I=="H"){I=1;for(var ma=T[q];I<ma;I++)T[I]*=k}else if(I=="V"){I=1;for(ma=T[q];I<ma;I++)T[I]*=m}else{I=1;for(ma=T[q];I<ma;I++)T[I]*=I%2?k:m}}}d=Aa(o);f=h-d.x-d.width/2;d=i-d.y-d.height/2;o[0][1]+=f;o[0][2]+=d;this.attr({path:o})}if(this.type in{text:1,image:1}&&(j!=1||n!=1))if(this.transformations){this.transformations[2]="scale(".concat(j,",",n,")");this.node.setAttribute("transform",this.transformations[O](L));f=j==-1?-g.x-(s||0):g.x;d=n==-1?-g.y-(H||0):g.y;this.attr({x:f,y:d});g.fx=
j-1;g.fy=n-1}else{this.node.filterMatrix=" progid:DXImageTransform.Microsoft"+".Matrix(M11=".concat(j,", M12=0, M21=0, M22=",n,", Dx=0, Dy=0, sizingmethod='auto expand', filtertype='bilinear')");r.filter=(this.node.filterMatrix||"")+(this.node.filterOpacity||"")}else if(this.transformations){this.transformations[2]="";this.node.setAttribute("transform",this.transformations[O](L));g.fx=0;g.fy=0}else{this.node.filterMatrix="";r.filter=(this.node.filterMatrix||"")+(this.node.filterOpacity||"")}g.scale=
[a,b,c,e][O](L);this._.sx=a;this._.sy=b}return this};B.clone=function(){if(this.removed)return null;var a=this.attr();delete a.scale;delete a.translation;return this.paper[this.type]().attr(a)};var Oa={},Da=function(a,b,c,e,f,d,g,j,h){var i=0,k=100,m=[a,b,c,e,f,d,g,j].join(),n=Oa[m],p,w;!n&&(Oa[m]=n={data:[]});n.timer&&clearTimeout(n.timer);n.timer=setTimeout(function(){delete Oa[m]},2E3);if(h!=null)k=~~Da(a,b,c,e,f,d,g,j)*10;for(var r=0;r<k+1;r++){if(n.data[h]>r)w=n.data[r*k];else{w=l.findDotsAtSegment(a,
b,c,e,f,d,g,j,r/k);n.data[r]=w}r&&(i+=G(G(p.x-w.x,2)+G(p.y-w.y,2),0.5));if(h!=null&&i>=h)return w;p=w}if(h==null)return i};pa=function(a,b){return function(c,e,f){c=za(c);for(var d,g,j,h,i="",k={},m=0,n=0,p=c.length;n<p;n++){j=c[n];if(j[0]=="M"){d=+j[1];g=+j[2]}else{h=Da(d,g,j[1],j[2],j[3],j[4],j[5],j[6]);if(m+h>e){if(b&&!k.start){d=Da(d,g,j[1],j[2],j[3],j[4],j[5],j[6],e-m);i+=["C",d.start.x,d.start.y,d.m.x,d.m.y,d.x,d.y];if(f)return i;k.start=i;i=["M",d.x,d.y+"C",d.n.x,d.n.y,d.end.x,d.end.y,j[5],
j[6]][O]();m+=h;d=+j[5];g=+j[6];continue}if(!a&&!b){d=Da(d,g,j[1],j[2],j[3],j[4],j[5],j[6],e-m);return{x:d.x,y:d.y,alpha:d.alpha}}}m+=h;d=+j[5];g=+j[6]}i+=j}k.end=i;d=a?m:b?k:l.findDotsAtSegment(d,g,j[1],j[2],j[3],j[4],j[5],j[6],1);d.alpha&&(d={x:d.x,y:d.y,alpha:d.alpha});return d}};var mb=pa(1),Ea=pa(),Pa=pa(0,1);B.getTotalLength=function(){if(this.type=="path"){if(this.node.getTotalLength)return this.node.getTotalLength();return mb(this.attrs.path)}};B.getPointAtLength=function(a){if(this.type==
"path")return Ea(this.attrs.path,a)};B.getSubpath=function(a,b){if(this.type=="path"){if(M(this.getTotalLength()-b)<"1e-6")return Pa(this.attrs.path,a).end;var c=Pa(this.attrs.path,b,1);return a?Pa(c,a).end:c}};l.easing_formulas={linear:function(a){return a},"<":function(a){return G(a,3)},">":function(a){return G(a-1,3)+1},"<>":function(a){a*=2;if(a<1)return G(a,3)/2;a-=2;return(G(a,3)+2)/2},backIn:function(a){return a*a*(2.70158*a-1.70158)},backOut:function(a){a-=1;return a*a*(2.70158*a+1.70158)+
1},elastic:function(a){if(a==0||a==1)return a;return G(2,-10*a)*y.sin((a-0.075)*2*S/0.3)+1},bounce:function(a){if(a<1/2.75)a*=7.5625*a;else if(a<2/2.75){a-=1.5/2.75;a=7.5625*a*a+0.75}else if(a<2.5/2.75){a-=2.25/2.75;a=7.5625*a*a+0.9375}else{a-=2.625/2.75;a=7.5625*a*a+0.984375}return a}};var ba=[],nb=function(){for(var a=+new Date,b=0;b<ba[q];b++){var c=ba[b];if(!(c.stop||c.el.removed)){var e=a-c.start,f=c.ms,d=c.easing,g=c.from,j=c.diff,h=c.to,i=c.t,k=c.el;c={};var m;if(e<f){e=d(e/f);for(var n in g)if(g[t](n)){switch(Ha[n]){case "along":m=
e*f*j[n];h.back&&(m=h.len-m);d=Ea(h[n],m);k.translate(j.sx-j.x||0,j.sy-j.y||0);j.x=d.x;j.y=d.y;k.translate(d.x-j.sx,d.y-j.sy);h.rot&&k.rotate(j.r+d.alpha,d.x,d.y);break;case N:m=+g[n]+e*f*j[n];break;case "colour":m="rgb("+[Qa(P(g[n].r+e*f*j[n].r)),Qa(P(g[n].g+e*f*j[n].g)),Qa(P(g[n].b+e*f*j[n].b))][O](",")+")";break;case "path":m=[];d=0;for(var p=g[n][q];d<p;d++){m[d]=[g[n][d][0]];for(var w=1,r=g[n][d][q];w<r;w++)m[d][w]=+g[n][d][w]+e*f*j[n][d][w];m[d]=m[d][O](L)}m=m[O](L);break;case "csv":switch(n){case "translation":m=
e*f*j[n][0]-i.x;d=e*f*j[n][1]-i.y;i.x+=m;i.y+=d;m=m+L+d;break;case "rotation":m=+g[n][0]+e*f*j[n][0];g[n][1]&&(m+=","+g[n][1]+","+g[n][2]);break;case "scale":m=[+g[n][0]+e*f*j[n][0],+g[n][1]+e*f*j[n][1],2 in h[n]?h[n][2]:"",3 in h[n]?h[n][3]:""][O](L);break;case "clip-rect":m=[];for(d=4;d--;)m[d]=+g[n][d]+e*f*j[n][d]}break;default:p=[].concat(g[n]);m=[];for(d=k.paper.customAttributes[n].length;d--;)m[d]=+p[d]+e*f*j[n][d]}c[n]=m}k.attr(c);k._run&&k._run.call(k)}else{if(h.along){d=Ea(h.along,h.len*
!h.back);k.translate(j.sx-(j.x||0)+d.x-j.sx,j.sy-(j.y||0)+d.y-j.sy);h.rot&&k.rotate(j.r+d.alpha,d.x,d.y)}(i.x||i.y)&&k.translate(-i.x,-i.y);h.scale&&(h.scale+="");k.attr(h);ba.splice(b--,1)}}}l.svg&&k&&k.paper&&k.paper.safari();ba[q]&&setTimeout(nb)},Lb=function(a,b,c,e,f){var d=c-e;b.timeouts.push(setTimeout(function(){l.is(f,"function")&&f.call(b);b.animate(a,d,a.easing)},e))},Qa=function(a){return W(ca(a,255),0)},Ca=function(a,b){if(a==null)return{x:this._.tx,y:this._.ty,toString:V};this._.tx+=
+a;this._.ty+=+b;switch(this.type){case "circle":case "ellipse":this.attr({cx:+a+this.attrs.cx,cy:+b+this.attrs.cy});break;case "rect":case "image":case "text":this.attr({x:+a+this.attrs.x,y:+b+this.attrs.y});break;case "path":var c=Ja(this.attrs.path);c[0][1]+=+a;c[0][2]+=+b;this.attr({path:c})}return this};B.animateWith=function(a,b,c,e,f){for(var d=0,g=ba.length;d<g;d++)if(ba[d].el.id==a.id)b.start=ba[d].start;return this.animate(b,c,e,f)};B.animateAlong=fa();B.animateAlongBack=fa(1);B.onAnimation=
function(a){this._run=a||0;return this};B.animate=function(a,b,c,e){var f=this;f.timeouts=f.timeouts||[];if(l.is(c,"function")||!c)e=c||null;if(f.removed){e&&e.call(f);return f}var d={},g={},j=false,h={},i;for(i in a)if(a[t](i))if(Ha[t](i)||f.paper.customAttributes[t](i)){j=true;d[i]=f.attr(i);d[i]==null&&(d[i]=wa[i]);g[i]=a[i];switch(Ha[i]){case "along":var k=mb(a[i]),m=Ea(a[i],k*!!a.back),n=f.getBBox();h[i]=k/b;h.tx=n.x;h.ty=n.y;h.sx=m.x;h.sy=m.y;g.rot=a.rot;g.back=a.back;g.len=k;a.rot&&(h.r=x(f.rotate())||
0);break;case N:h[i]=(g[i]-d[i])/b;break;case "colour":d[i]=l.getRGB(d[i]);k=l.getRGB(g[i]);h[i]={r:(k.r-d[i].r)/b,g:(k.g-d[i].g)/b,b:(k.b-d[i].b)/b};break;case "path":k=za(d[i],g[i]);d[i]=k[0];n=k[1];h[i]=[];k=0;for(m=d[i][q];k<m;k++){h[i][k]=[0];for(var p=1,w=d[i][k][q];p<w;p++)h[i][k][p]=(n[k][p]-d[i][k][p])/b}break;case "csv":m=A(a[i]).split(R);n=A(d[i]).split(R);switch(i){case "translation":d[i]=[0,0];h[i]=[m[0]/b,m[1]/b];break;case "rotation":d[i]=n[1]==m[1]&&n[2]==m[2]?n:[0,m[1],m[2]];h[i]=
[(m[0]-d[i][0])/b,0,0];break;case "scale":a[i]=m;d[i]=A(d[i]).split(R);h[i]=[(m[0]-d[i][0])/b,(m[1]-d[i][1])/b,0,0];break;case "clip-rect":d[i]=A(d[i]).split(R);h[i]=[];for(k=4;k--;)h[i][k]=(m[k]-d[i][k])/b}g[i]=m;break;default:m=[].concat(a[i]);n=[].concat(d[i]);h[i]=[];for(k=f.paper.customAttributes[i][q];k--;)h[i][k]=((m[k]||0)-(n[k]||0))/b}}if(j){i=l.easing_formulas[c];if(!i)if((i=A(c).match(rb))&&i[q]==5){var r=i;i=function(H){return ea(H,+r[1],+r[2],+r[3],+r[4],b)}}else i=function(H){return H};
ba.push({start:a.start||+new Date,ms:b,easing:i,from:d,diff:h,to:g,el:f,t:{x:0,y:0}});l.is(e,"function")&&(f._ac=setTimeout(function(){e.call(f)},b));ba[q]==1&&setTimeout(nb)}else{c=[];var o,s;for(s in a)if(a[t](s)&&sb.test(s)){i={value:a[s]};s=="from"&&(s=0);s=="to"&&(s=100);i.key=ga(s,10);c.push(i)}c.sort(xb);c[0].key&&c.unshift({key:0,value:f.attrs});k=0;for(m=c[q];k<m;k++)Lb(c[k].value,f,b/100*c[k].key,b/100*(c[k-1]&&c[k-1].key||0),c[k-1]&&c[k-1].value.callback);(o=c[c[q]-1].value.callback)&&
f.timeouts.push(setTimeout(function(){o.call(f)},b))}return this};B.stop=function(){for(var a=0;a<ba.length;a++)ba[a].el.id==this.id&&ba.splice(a--,1);a=0;for(ii=this.timeouts&&this.timeouts.length;a<ii;a++)clearTimeout(this.timeouts[a]);this.timeouts=[];clearTimeout(this._ac);delete this._ac;return this};B.translate=function(a,b){return this.attr({translation:a+" "+b})};B[da]=function(){return"Rapha\u00ebl\u2019s object"};l.ae=ba;var Y=function(a){this.items=[];this[q]=0;this.type="set";if(a)for(var b=0,c=
a[q];b<c;b++)if(a[b]&&(a[b].constructor==D||a[b].constructor==Y)){this[this.items[q]]=this.items[this.items[q]]=a[b];this[q]++}};Y[z][F]=function(){for(var a,b,c=0,e=arguments[q];c<e;c++)if((a=arguments[c])&&(a.constructor==D||a.constructor==Y)){b=this.items[q];this[b]=this.items[b]=a;this[q]++}return this};Y[z].pop=function(){delete this[this[q]--];return this.items.pop()};for(var Ra in B)if(B[t](Ra))Y[z][Ra]=function(a){return function(){for(var b=0,c=this.items[q];b<c;b++)this.items[b][a][C](this.items[b],
arguments);return this}}(Ra);Y[z].attr=function(a,b){if(a&&l.is(a,X)&&l.is(a[0],"object"))for(var c=0,e=a[q];c<e;c++)this.items[c].attr(a[c]);else{c=0;for(e=this.items[q];c<e;c++)this.items[c].attr(a,b)}return this};Y[z].animate=function(a,b,c,e){(l.is(c,"function")||!c)&&(e=c||null);var f=this.items[q],d=f,g,j=this,h;e&&(h=function(){!--f&&e.call(j)});c=l.is(c,"string")?c:h;for(g=this.items[--d].animate(a,b,c,h);d--;)this.items[d]&&!this.items[d].removed&&this.items[d].animateWith(g,a,b,c,h);return this};
Y[z].insertAfter=function(a){for(var b=this.items[q];b--;)this.items[b].insertAfter(a);return this};Y[z].getBBox=function(){for(var a=[],b=[],c=[],e=[],f=this.items[q];f--;){var d=this.items[f].getBBox();a[F](d.x);b[F](d.y);c[F](d.x+d.width);e[F](d.y+d.height)}a=ca[C](0,a);b=ca[C](0,b);return{x:a,y:b,width:W[C](0,c)-a,height:W[C](0,e)-b}};Y[z].clone=function(a){a=new Y;for(var b=0,c=this.items[q];b<c;b++)a[F](this.items[b].clone());return a};l.registerFont=function(a){if(!a.face)return a;this.fonts=
this.fonts||{};var b={w:a.w,face:{},glyphs:{}},c=a.face["font-family"],e;for(e in a.face)if(a.face[t](e))b.face[e]=a.face[e];if(this.fonts[c])this.fonts[c][F](b);else this.fonts[c]=[b];if(!a.svg){b.face["units-per-em"]=ga(a.face["units-per-em"],10);for(var f in a.glyphs)if(a.glyphs[t](f)){c=a.glyphs[f];b.glyphs[f]={w:c.w,k:{},d:c.d&&"M"+c.d.replace(/[mlcxtrv]/g,function(g){return{l:"L",c:"C",x:"z",t:"m",r:"l",v:"c"}[g]||"M"})+"z"};if(c.k)for(var d in c.k)if(c[t](d))b.glyphs[f].k[d]=c.k[d]}}return a};
E.getFont=function(a,b,c,e){e=e||"normal";c=c||"normal";b=+b||{normal:400,bold:700,lighter:300,bolder:800}[b]||400;if(l.fonts){var f=l.fonts[a];if(!f){a=RegExp("(^|\\s)"+a.replace(/[^\w\d\s+!~.:_-]/g,"")+"(\\s|$)","i");for(var d in l.fonts)if(l.fonts[t](d))if(a.test(d)){f=l.fonts[d];break}}var g;if(f){d=0;for(a=f[q];d<a;d++){g=f[d];if(g.face["font-weight"]==b&&(g.face["font-style"]==c||!g.face["font-style"])&&g.face["font-stretch"]==e)break}}return g}};E.print=function(a,b,c,e,f,d,g){d=d||"middle";
g=W(ca(g||0,1),-1);var j=this.set(),h=A(c).split(""),i=0;l.is(e,c)&&(e=this.getFont(e));if(e){c=(f||16)/e.face["units-per-em"];var k=e.face.bbox.split(R);f=+k[0];d=+k[1]+(d=="baseline"?k[3]-k[1]+ +e.face.descent:(k[3]-k[1])/2);k=0;for(var m=h[q];k<m;k++){var n=k&&e.glyphs[h[k-1]]||{},p=e.glyphs[h[k]];i+=k?(n.w||e.w)+(n.k&&n.k[h[k]]||0)+e.w*g:0;p&&p.d&&j[F](this.path(p.d).attr({fill:"#000",stroke:"none",translation:[i,0]}))}j.scale(c,c,f,d).translate(a-f,b-d)}return j};l.format=function(a,b){var c=
l.is(b,X)?[0].concat(b):arguments;a&&l.is(a,"string")&&c[q]-1&&(a=a.replace(na,function(e,f){return c[++f]==null?"":c[f]}));return a||""};l.ninja=function(){ka.was?K.Raphael=ka.is:delete Raphael;return l};l.el=B;l.st=Y[z];ka.was?K.Raphael=l:Raphael=l})();
(function(){window.ScaleRaphael=function(l,Z,J){var V=typeof l=="string"?document.getElementById(l):l;if(!V.style.position)V.style.position="relative";V.style.width=Z+"px";V.style.height=J+"px";V.style.overflow="hidden";var fa;if(Raphael.type=="VML"){V.innerHTML="<rvml:group style='position : absolute; width: 1000px; height: 1000px; top: 0px; left: 0px' coordsize='1000,1000' class='rvml' id='vmlgroup'></rvml:group>";fa=document.getElementById("vmlgroup")}else{V.innerHTML="<div id='svggroup'></div>";
fa=document.getElementById("svggroup")}var ea=new Raphael(fa,Z,J),R;if(Raphael.type=="SVG")ea.canvas.setAttribute("viewBox","0 0 "+Z+" "+J);else R=V.getElementsByTagName("div")[0];ea.changeSize=function(ha,na,z,t){t=!t;var v=ha/Z,K=na/J,ka=v<K?v:K;v=parseInt(J*ka);K=parseInt(Z*ka);if(Raphael.type=="VML"){var la=document.getElementsByTagName("textpath"),E;for(E in la){var C=la[E];if(C.style){if(!C._fontSize){var oa=C.style.font.split("px");C._fontSize=parseInt(oa[0]);C._font=oa[1]}C.style.font=C._fontSize*
ka+"px"+C._font}}E=K<v?K*1E3/Z:v*1E3/J;E=parseInt(E);fa.style.width=E+"px";fa.style.height=E+"px";if(t){fa.style.left=parseInt((ha-K)/2)+"px";fa.style.top=parseInt((na-v)/2)+"px"}R.style.overflow="visible"}if(t){K=ha;v=na}V.style.width=K+"px";V.style.height=v+"px";ea.setSize(K,v);if(z){V.style.position="absolute";V.style.left=parseInt((ha-K)/2)+"px";V.style.top=parseInt((na-v)/2)+"px"}};ea.scaleAll=function(ha){ea.changeSize(Z*ha,J*ha)};ea.changeSize(Z,J);ea.w=Z;ea.h=J;return ea}})();
