/*
Copyright 2012, A+ v1.0.0
build time: Jun 18 16:35
*/
var createShape=function(){function s(n,p,t,q,h,d,a){n=n.path(p);var b=n.attrs;n.X=b.x=t;n.Y=b.y=q;n.W=b.width=h;n.H=b.height=d;if(a)n.R=b.r=a;n.path=b.path=p;n.type="path";return n}function w(n,p,t,q,h,d,a){h=h?h:0;d=d&&d>0?d:12;a=a&&a>0?a:12;q=Math.tan(Raphael.rad((q&&q>0?q:50)/2))*d;var b=p-q,c=t-d;n=s(n,["M",p,t,"L",b,c,"L",p,t-a,"L",p+q,c,"Z"],b,c,2*q,d);n.rotate(h,p,t);return n}return{Hexagon:function(n,p,t,q,h,d){return s(n,["M",p||0,t||0,"l",(q||0)-2*(d||0),0,d||0,Math.floor((h||0)/2),-(d||
0),Math.floor((h||0)/2),2*(d||0)-(q||0),0,-(d||0),Math.floor(-(h||0)/2),"z"],p||0,t||0,q||0,h||0)},Rhombus:function(n,p,t,q,h){return s(n,["M",p||0,t||0,"l",Math.floor((q||0)/2),Math.floor((h||0)/2),Math.floor(-(q||0)/2),Math.floor((h||0)/2),Math.floor(-(q||0)/2),Math.floor(-(h||0)/2),"z"],p||0,t||0,q||0,h||0)},Rects:function(n,p,t,q,h){return s(n,["M",p||0,t||0,"l",q||0,0,0,h||0,-(q||0),0,"z m",10,0,"l0",h||0,"m",(q||0)-20,0,"l0",-(h||0)],p||0,t||0,q||0,h||0)},Triangle:function(n,p,t,q,h,d){return w(n,
p||0,t||0,q||0,h||0,d||0,d||0)},Arrow:function(n,p,t,q,h,d,a){return w(n,p||0,t||0,q,h,d,a)}}}();Raphael.fn.Hexagon=function(s,w,n,p,t){return createShape.Hexagon(this,s,w,n,p,t)};Raphael.fn.Rhombus=function(s,w,n,p){return createShape.Rhombus(this,s,w,n,p)};Raphael.fn.DoubleRects=function(s,w,n,p){return createShape.Rects(this,s,w,n,p)};Raphael.fn.Arrow=function(s,w,n,p,t,q){return createShape.Arrow(this,s,w,n,p,t,q)};
Raphael.fn.Triangle=function(s,w,n,p,t){return createShape.Triangle(this,s,w,n,p,t)};
var cedge=function(){function s(d,a,b,c,e){var o=d==="ee",i=o?a.left>b.right:b.left>a.right;d=o?1:-1;if((o?a.right<b.left:b.right<a.left)&&b.bottom>=c.y&&b.top<c.y){i=o?b.left-a.right:a.left-b.right;i=c.x+i/2*d;a=o?b.top-24:b.bottom+24;h=["L",i,c.y,i,a,e.x+24*d,a,e.x+24*d,e.y]}else if(e.y>a.top&&e.y<a.bottom&&i){i=o?a.left-b.right:b.left-a.right;i=e.x+i/2*d;a=o?a.bottom+24:a.top-24;h=["L",c.x+24*d,c.y,c.x+24*d,a,i,a,i,e.y]}else{i=o?Math.max(a.right,b.right):Math.min(a.left,b.left);h=["L",i+24*d,c.y,
i+24*d,e.y]}return h}function w(d,a,b,c,e){var o=d==="nn",i=o?b.top>a.bottom:b.bottom<a.top;d=o?-1:1;if((o?b.bottom<a.top:b.top>a.bottom)&&b.right>=c.x&&b.left<c.x){i=o?a.top-b.bottom:b.top-a.bottom;i=c.y+i/2*d;a=o?b.left-24:b.right+24;h=["L",c.x,i,a,i,a,e.y+24*d,e.x,e.y+24*d]}else if(e.x>a.left&&e.x<a.right&&i){i=o?b.top-a.bottom:a.top-b.bottom;i=e.y+i/2*d;a=o?a.right+24:a.left-24;h=["L",c.x,c.y+24*d,a,c.y+24*d,a,i,e.x,i]}else{i=o?Math.min(a.top,b.top):Math.max(a.bottom,b.bottom);h=["L",c.x,i+24*
d,e.x,i+24*d]}return h}function n(d,a,b,c,e){var o=d==="n",i=o?c.y>=e.y:c.y<=e.y,C=o?e.y>c.y:e.y<c.y,E=o?b.bottom<a.top:b.top>a.bottom;d=o?1:-1;if(c.x<=e.x&&i)h=["L",c.x,e.y];else if(C&&a.right<=b.left){o=(b.left-a.right)/2;h=["L",c.x,c.y-24*d,e.x-o,c.y-24*d,e.x-o,e.y]}else if(b.left<c.x&&E){o=o?a.top-b.bottom:b.top-a.bottom;o/=2;a=Math.min(a.left,b.left);h=["L",c.x,c.y-o*d,a-24,c.y-o*d,a-24,e.y]}else{o=Math.min(a.left,b.left);h=["L",c.x,c.y-24*d,o-24,c.y-24*d,o-24,e.y]}return h}function p(d,a,b,
c,e){var o=d==="n",i=o?c.y>=e.y:c.y<=e.y,C=o?b.bottom<a.top:b.top>a.bottom;d=o?1:-1;if(c.x>=e.x&&i)h=["L",c.x,e.y];else if(e.y<c.y&&b.right<=a.left){i=(a.left-b.right)/2;h=["L",c.x,c.y-24*d,e.x+i,c.y-24*d,e.x+i,e.y]}else if(e.y>c.y&&b.right<=a.left){i=(a.left-b.right)/2;h=["L",c.x,c.y-24*d,e.x+i,c.y-24*d,e.x+i,e.y]}else if(b.right>c.x&&C){i=o?a.top-b.bottom:b.top-a.bottom;i/=2;a=o?e.x:Math.max(a.right,b.right);h=["L",c.x,c.y-i*d,a+24,c.y-i*d,a+24,e.y]}else{i=Math.max(a.right,b.right);h=["L",c.x,c.y-
24*d,i+24,c.y-24*d,i+24,e.y]}return h}function t(d,a,b,c){if(c.y>b.y)if(c.x===b.x)h=["L"];else{var e=(c.y-b.y)/2;h=["L",b.x,b.y+e,c.x,c.y-e]}else if(c.y<=b.y)if(a.right<d.left){e=(d.left-a.right)/2;h=["L",b.x,b.y+24,e+a.right,b.y+24,e+a.right,c.y-24,c.x,c.y-24]}else if(a.left>d.right){e=(a.left-d.right)/2;h=["L",b.x,b.y+24,e+d.right,b.y+24,e+d.right,c.y-24,c.x,c.y-24]}else if(c.x<=b.x){e=Math.min(a.left,d.left);h=["L",b.x,b.y+24,e-24,b.y+24,e-24,c.y-24,c.x,c.y-24]}else{e=Math.max(a.right,d.right);
h=["L",b.x,b.y+24,e+24,b.y+24,e+24,c.y-24,c.x,c.y-24]}return h}function q(d,a,b,c){if(a.left>=d.right)if(c.y===b.y)h=["L",b.x,b.y];else{var e=(a.left-d.right)/2;h=["L",b.x+e,b.y,b.x+e,c.y]}else if(a.top<d.bottom&&b.y<=c.y){e=Math.max(d.bottom,a.bottom);h=["L",b.x+24,b.y,b.x+24,e+24,c.x-24,e+24,c.x-24,c.y]}else if(b.y>c.y&&d.top<a.bottom){e=Math.min(d.top,a.top);h=["L",b.x+24,b.y,b.x+24,e-24,c.x-24,e-24,c.x-24,c.y]}else if(a.top>=d.bottom){e=(a.top-d.bottom)/2;h=["L",b.x+24,b.y,b.x+24,d.bottom+e,c.x-
24,d.bottom+e,c.x-24,c.y]}else{e=(d.top-a.bottom)/2;h=["L",b.x+24,b.y,b.x+24,a.bottom+e,c.x-24,a.bottom+e,c.x-24,c.y]}return h}var h=[];return{ee:function(d,a,b,c){return{a:s("ee",d,a,b,c),r:false}},ww:function(d,a,b,c){return{a:s("ww",d,a,b,c),r:false}},nn:function(d,a,b,c){return{a:w("nn",d,a,b,c),r:false}},ss:function(d,a,b,c){return{a:w("ss",d,a,b,c),r:false}},nw:function(d,a,b,c){return{a:n("n",d,a,b,c),r:false}},wn:function(d,a,b,c){return{a:n("n",a,d,c,b),r:true}},sw:function(d,a,b,c){return{a:n("s",
d,a,b,c),r:false}},ws:function(d,a,b,c){return{a:n("s",a,d,c,b),r:true}},ne:function(d,a,b,c){return{a:p("n",d,a,b,c),r:false}},en:function(d,a,b,c){return{a:p("n",a,d,c,b),r:true}},se:function(d,a,b,c){return{a:p("s",d,a,b,c),r:false}},es:function(d,a,b,c){return{a:p("s",a,d,c,b),r:true}},sn:function(d,a,b,c){return{a:t(d,a,b,c),r:false}},ns:function(d,a,b,c){return{a:t(a,d,c,b),r:true}},ew:function(d,a,b,c){return{a:q(d,a,b,c),r:false}},we:function(d,a,b,c){return{a:q(a,d,c,b),r:true}}}}(),lrShape=
function(){function s(k){return parseInt(k,10)}function w(k,g,j,f,m){if(g){g=a.text(j,f,g.replace(/&#xa;/g,"\n"));if(m=="toBack")g.toBack();else m=="toFront"&&g.toFront();if(k){k=(";"+k).split(";");k.push("font-family=\u5b8b\u4f53");h(g,k)}return g}}function n(k,g){var j,f,m=s(g.x),l=s(g.y),x=s(g.w),z=s(g.h),A=s(g.r),B=m+Math.floor(x/2),y=l+Math.floor(z/2),u,r=g.pdp.split("|"),v;if(typeof k==="string"){j=k.split(";");f=j[0];switch(f){case "rect":u=a.rect(m,l,x,z);break;case "rects":u=a.DoubleRects(m,l,x,z);
break;case "rounded":u=a.rect(m,l,x,z,A);break;case "triangle":u=a.Triangle(m,l,x,z,A);break;case "rhombus":u=a.Rhombus(m,l,x,z);B=m;break;case "arrow":u=a.Arrow(m,l,fAngle,deltaAngle,len,sLen);break;case "hexagon":u=a.Hexagon(m,l,x,z,A);B=m+Math.floor(x/2-A)}m="wf"+(g.id?g.id:YH.genId("graph"));l=function(D){D.click(function(){if(i&&i.node.id!=this.node.id){v=s(i.attr("stroke-width"));if(isNaN(v))v=1;v=v===2?1:2;i.attr({"stroke-width":v,stroke:C});i=C=null}i||(i=this);C||(C=this.attr("stroke"));
v=s(this.attr("stroke-width"));if(isNaN(v))v=1;v=v<=2?1:1.5;this.attr({"stroke-width":v*2,stroke:"#1a2af7"});e&&e.call(this)}).mouseover(function(){if(!i||i.node.id!=this.node.id){v=s(this.attr("stroke-width"));if(isNaN(v))v=1;v=v===1?1:1.5;this.attr({"stroke-width":v*2})}}).mouseout(function(){if(!i||i.node.id!=this.node.id){v=s(this.attr("stroke-width"));if(isNaN(v))v=1;v=v===2?1:2;this.attr("stroke-width",v)}})};if(u){u.attr({isShape:f});u.node.id=m;F.showtitle&&g.label&&u.attr("title",g.label);
if(r[1]&&r[1]==="0"){u.attr("cursor","pointer");u.dblclick(function(){E&&E.call(this)});l(u)}}w(g.lstyle,g.label,B,y);b[m]={id:m,rp:u,label:g.label,pid:r[0]+"",dis:r[1]+"",isPoints:r[2]+"",points:g.points};if(r[2]&&r[2]==="1")o[m]=b[m];j.length>1&&h(u,j);return u}}function p(k,g){var j=0,f=0;switch(k){case "n":j=g.x+g.width/2;f=g.y;break;case "s":j=g.x+g.width/2;f=g.y+g.height;break;case "e":j=g.x+g.width;f=g.y+g.height/2;break;case "w":j=g.x;f=g.y+g.height/2}return{x:j,y:f}}function t(k,g){var j,
f,m,l,x=null,z=null,A,B,y,u,r,v=k.path;j=k.from.split("|");f=k.to.split("|");m=j[1];j=j[0];l=f[1];f=f[0];if(j==="x"||f==="x"){var D=v.split(",");if(j==="x")y={x:s(D[1])||0,y:s(D[2])||0};if(f==="x")u={x:s(D[D.length-2])||0,y:s(D[D.length-1])||0}}if(j!="x")x=b["wf"+j].rp;if(f!="x")z=b["wf"+f].rp;if(j!="x"){A=c["wf"+j];if(!A){r=x.getBBox();A={top:r.y,right:r.x+r.width,bottom:r.y+r.height,left:r.x,width:r.width,height:r.height};c["wf"+j]=A}r=p(m,A!="undefined"?x.getBBox():r);y={x:r.x,y:r.y}}if(f!="x"){B=
c["wf"+f];if(!B){r=z.getBBox();B={top:r.y,right:r.x+r.width,bottom:r.y+r.height,left:r.x,width:r.width,height:r.height};c["wf"+f]=B}r=p(l,B!="undefined"?z.getBBox():r);u={x:r.x,y:r.y}}if(v)j=j==="x"?v+",L"+u.x+","+u.y:f==="x"?"M"+y.x+","+y.y+","+k.path:"M"+y.x+","+y.y+","+k.path+",L"+u.x+","+u.y;else{j=cedge[m+l](A,B,y,u);j=j.r?["M",u.x,u.y].concat(j.a,[y.x,y.y]):["M",y.x,y.y].concat(j.a,[u.x,u.y])}j=a.path(j);if(g){f=g.split(";");f[0]==="twoway"&&q(m,y,"#4979cb",k.arrowOffset);f[0]!="noway"&&q(l,
u,"#4979cb",k.arrowOffset);f[0]==="toback"&&j.toBack();h(j,f)}else q(l,u,"#000",k.arrowOffset);return j}function q(k,g,j,f){var m=0,l=0;g=a.Arrow(g.x,g.y,50,{n:0,s:180,e:90,w:-90}[k],6,6).attr({fill:j,stroke:j});if(f>0)if(k==="n")l=-1;else if(k==="s")l=1;else if(k==="w")m=-1;else if(k==="e")m=1;g.translate(f*m,f*l);return g}function h(k,g){var j=1,f,m={},l;for(l=false;f=g[j];++j){f=f.split("=");l=f[0];f=f[1];m[l]=typeof f=="number"?s(f):String(f);l=true}l&&k.attr(m)}var d,a,b={},c={},e,o={},i=null,
C=null,E,F,G={};return{init:function(k){F=k||{};a=F.p;e=F.callback;E=F.dblcallback;if(!a){alert("error:\u672a\u521d\u59cb\u5316canvas");return false}return true},analysisNode:function(k){d=k.getElementsByTagName("Workflow")[0];for(k=d.nextSibling;k;){if(k.nodeType<3){var g=k,j=g.nodeName,f={},m=void 0,l=void 0,x=void 0;m=g.firstChild;l=m.firstChild;if(!YH.userAgent.isIE){for(;m;){if(m.nodeName==="rCell")break;m=m.nextSibling}for(l=m.firstChild;l;){if(l.nodeName==="rGeometry")break;l=l.nextSibling}}f.label=g.getAttribute("label")+
"";f.pdp=g.getAttribute("pdp")+"";f.id=g.getAttribute("id")||YH.genId("graph");f.lstyle=g.getAttribute("lstyle")+"";f.points=g.getAttribute("points")||"0";x=m.getAttribute("style");switch(j){case "Swimlane":g=l.getAttribute("x");j=l.getAttribute("y");f=l.getAttribute("width");l=l.getAttribute("height");m=a.path(l=="0"?["M",g,j,"L",f,j]:["M",g,j,"L",g,l]);h(m,x.split(";"));break;case "Shape":f.x=l.getAttribute("x");f.y=l.getAttribute("y");f.w=l.getAttribute("width");f.h=l.getAttribute("height");f.r=
l.getAttribute("radius");n(x,f);break;case "Edge":f.from=m.getAttribute("source");f.to=m.getAttribute("target");f.path=m.getAttribute("path")||"";f.arrowOffset=s(l.getAttribute("arrowOffset")||0);t(f,x);break;case "Label":f.x=l.getAttribute("x");f.y=l.getAttribute("y");w(x,f.label,f.x,f.y);G[f.id]={id:f.id,label:f.label}}}k=k.nextSibling}},setNodes:function(k){b=k},getNodes:function(){return b},getPoints:function(){return o},getLabels:function(){return G},renderShape:function(k,g){return n(k,g)},
renderLabel:function(k,g,j,f,m){return w(k,g,j,f,m)},renderEdge:function(k,g){return t(k,g)},makeArrow:function(k,g,j,f){return q(k,g,j,f)}}}();
